### ISSUE TITLE
logger.Error needs a context

### ISSUE THREAD

**Issue by panol** [go-micro/go-micro#2269]
**Is your feature request related to a problem? Please describe.**

I am trace all of my log with one traceID,but in 

https://github.com/asim/go-micro/blob/master/plugins/server/grpc/grpc.go

defer func() {
				if r := recover(); r != nil {
					if logger.V(logger.ErrorLevel, logger.DefaultLogger) {
						logger.Error("panic recovered: ", r)
						logger.Error(string(debug.Stack()))
					}
					err = errors.InternalServerError("go.micro.server", "panic recovered: %v", r)
				}
			}()

logger.Error("panic recovered: ", r)
logger.Error(string(debug.Stack()))

I want to bind the debug.Stack() with the traceId
but doenn't have a way to add tracdId 
so it is impossible for me to trace the log with traceId,and hence it will be hard to find the exact err log with tracdId 

**Describe the solution you'd like**

I want to bind the tracdId of our system with the error info which is what logger.Error("panic recovered: ", r) and logger.Error(string(debug.Stack()))  log 

**Additional context**

**Comment by gregkv** [comment]
@panol PR #2278 should solve this problem. In your service you just need to set logger with required fields to context. Here is an example that sets all context metadata to "context logger" (so in "panic recovered" error message we will see all of them).
```
func SetLoggerToContextWrapper() server.HandlerWrapper {
	return func(fn server.HandlerFunc) server.HandlerFunc {
		return func(ctx context.Context, req server.Request, rsp interface{}) error {
			md, _ := metadata.FromContext(ctx)
			
			fields := map[string]interface{}{}
			for k, v := range md {
				fields[k] = v
			}
			ctx = logger.NewContext(ctx, logger.DefaultLogger.Fields(fields))
			
			return fn(ctx, req, rsp)
		}
	}
}

func main() {
	service := micro.NewService(
		micro.Name("my-service"),
		micro.WrapHandler(SetLoggerToContextWrapper()),
	)
}
```

**Comment by panol** [comment]
It works!
Thanks~this feature solve my problem
