### ISSUE TITLE
Client calls to grpc methods report errors

### ISSUE THREAD

**Issue by xufei56789** [go-micro/go-micro#2291]
**error:**
{"id":"go.micro.client","code":500,"detail":"service billing_product: not found","status":"Internal Server Error"}

**Client code：**
type logWrapper struct {
	client.Client
}

func (l *logWrapper) Call(ctx context.Context, req client.Request, rsp interface{}, opts ...client.CallOption) error {
	md, _ := metadata.FromContext(ctx)
	fmt.Printf("[Log Wrapper] ctx: %v service: %s method: %s\n", md, req.Service(), req.Endpoint())
	return l.Client.Call(ctx, req, rsp)
}

func newLogWrapper(c client.Client) client.Client {
	return &logWrapper{c}
}

func main() {
	config.Init()
	etcdCnf := config.GetEtcdCnf()
	passlCnf := config.GetBillingOrderCnf()
	etcdReg := etcd.NewRegistry(
		registry.Addrs(etcdCnf.Addrs[0]),
	)
	myService  := micro.NewService(
		micro.Name("billing_product.client"),
		micro.WrapClient(newLogWrapper),
	)
	pro := api.NewProductService("billing_product", myService .Client())
	service := httpServer.NewServer(
		server.Name("billing_product.client"),
		server.Address(fmt.Sprintf(":%d", passlCnf.Port)),
		server.Registry(etcdReg),
	)
	hd := service.NewHandler(router.InitRouters())
	service.Handle(hd)
	srv := micro.NewService(
		micro.Server(service),
	)
	srv.Init()
	res, errs := pro.GetProduct(context.Background(), &api.ProductRequest{ProductId: 11})
	fmt.Println()
	fmt.Println(errs)
	fmt.Println(res)
	if err := srv.Run(); err != nil {
		log.Error(err.Error())
	}
}

**Comment by xufei56789** [comment]
**etcd info:**
 etcdctl get / --prefix --keys-only
/micro/registry/billing_product.client/billing_product.client-c635dfaf-f443-49f0-b449-1ea769fde626

/micro/registry/billing_product/billing_product-795a2cdd-321e-488b-8a3b-12ae577ea29b

**Comment by xufei56789** [comment]
billing_product Server side is running

**Comment by DMwangnima** [comment]
Try to use this code snippet, cause client library codes need registry module to find billing_product service.
`myService := micro.NewService(
micro.Name("billing_product.client"),
micro.WrapClient(newLogWrapper),
micro.Registry(etcdReg),
)`

**Comment by xufei56789** [comment]
Thank you very much, but now a new error is reported
{"id":"go.micro.client.transport","code":500,"detail":"404 Not Found: 404 page not found","status":"Internal Server Error"}
