### ISSUE TITLE
[FEATURE] BlobStore or just use Cache/Store ?

### ISSUE THREAD

**Issue by wenerme** [go-micro/go-micro#2292]
**Is your feature request related to a problem? Please describe.**

https://github.com/asim/go-micro/blob/09d6d0e2d22b7d342de713b762b982afe93396c6/store/blob.go#L14-L18

plus List operation and other common methods(Init,String,Close?).

**Describe the solution you'd like**

I don't know what happened to micro/go-micro or the original BlobStore, but a BlobStore is really fit for S3 and other object storage. use Store should be fine, but the default read return slice, most blob store return only one record. Blob sometime is quite large, but Store record only support bytes, this means must load all data in mem.

**Additional context**

**Comment by asim** [comment]
We didn't really have good implementations for the blob store interface and it was specifically for our own product requirements at the company. Now that this has gone back to being a personal project I ripped it out. 

Happy to accept a contribution where it makes sense along with some plugin implementations.

**Comment by wenerme** [comment]
Thanks for your quick reply, a blob store is very helpful, go-cloud's impl is a good reference https://github.com/google/go-cloud/blob/master/blob/blob.go , but kind complicated. I'll let this open, hope some day can work on this.
