### ISSUE TITLE
[FEATURE] Add MultiError type to errors package

### ISSUE THREAD

**Issue by Qalifah** [go-micro/go-micro#2294]
I was working on a project and at a point in time, i needed to store errors that i was getting in a loop and check after the loop was done. I realised the ability isn't present in go-micro and i feel it's something that would be useful. The MultiError type will have methods like:
> **Append** to add error, which satisfies the *error* interface.

>**HasErrors** to check if it contains any error. 

>**Error** that satisfies the *error* interface. 

what do you think about it.

**Comment by asim** [comment]
Yea welcome the feature

**Comment by Qalifah** [comment]
okay
