### ISSUE TITLE
Request for Maintainers

### ISSUE THREAD

**Issue by asim** [go-micro/go-micro#2313]
I'm not actively working on go-micro but I gatekeep it being the creator. It's still heavily used, 600k clones/month. For those who continue to use it and want to contribute, I'm looking for active maintainers. @xpunch has been added. Any others, let me know. You must be existing users of go-micro, you must have previously contributed.

**Comment by asim** [comment]
So far @xpunch, @AuditeMarlow and @Jackneill have been added as maintainers. All three are heavy users of go-micro and will make changes as needed.

**Comment by ecasilla** [comment]
I would love to help anyway I can

**Comment by asim** [comment]
Hey @ecasilla have you contributed to the project?

**Comment by JeffreyBool** [comment]
I can try, I've had time to contribute to this again recently, I've been working on the company's basic framework architecture and can put good ideas like go-micro

**Comment by JeffreyBool** [comment]
> 嘿@ecasilla你为这个项目做出了贡献吗？
May I?

**Comment by JeffreyBool** [comment]
@asim  May I?

**Comment by asim** [comment]
I can't make you a maintainer without actual contribution. Both people who have been made maintainers have been actively contributing. So feel free to contribute and then if everyone is happy we can add you.

**Comment by JeffreyBool** [comment]
> I can't make you a maintainer without actual contribution. Both people who have been made maintainers have been actively contributing. So feel free to contribute and then if everyone is happy we can add you.

Is there anything to do? Please give me a direction ？

**Comment by asim** [comment]
Have a look at the issues list. Otherwise people are contributing based on their own usage requirements. So if you're using it you'll have ideas.

**Comment by refs** [comment]
Hey @asim I could definitely lend a hand on this area. We've been using go-micro for over 2 years now and have contributed to the project. Regardless of us not using 100% the span of the features, I believe we can bring not only contribute with some ideas to the core concept of go-micro, being so deep on it as we are.

Feel free to reply here, or refer to me on Slack, or send me an email to hello@zyxan.io if I can help with something, whatever you have in mind.
