### ISSUE TITLE
[BUG]use plugins/registry/etcd get "grpc: error while marshaling ... is not type of *bytes.Frame or proto.Message"

### ISSUE THREAD

**Issue by bootfirst** [go-micro/go-micro#2333]
**Describe the bug**

use the latest plugins/registry/etcd(commit:62b985f49cc56cabc56aa4406eefe6c1e834bf93)
get error with "grpc: error while marshaling: failed to marshal: key:\"/micro/registry/xxxx\" serializable:true  is not type of *bytes.Frame or proto.Message"
```go
import (
	_ "github.com/asim/go-micro/plugins/client/grpc/v4"
	_ "github.com/asim/go-micro/plugins/registry/etcd/v4"
)
```

I guess the reason below:
in plugins/client/grpc/v4@v4.0.0-20211101214452-62b985f49cc5/grpc.go:39
```go
encoding.RegisterCodec(wrapCodec{protoCodec{}})
```
plugins/client/grpc/v4@v4.0.0-20211019191242-9edc569e68bb/codec.go:69
```go
switch m := v.(type) {
case *bytes.Frame:
	return m.Data, nil
case proto.Message:
	return proto.Marshal(m)
}
```
the latest proto.Message(google.golang.org/protobuf v1.26.0), the older is (github.com/golang/protobuf v1.5.2)

etcdv3.5.0(api/etcdserverpb/rpc.pb.go)use github.com/golang/protobuf v1.5.2(still use such an old version)

Anyone has better ideas to solve this problem?

**Comment by xpunch** [comment]
Seams an etcd issue, you can add this in your go.mod to fix this temporarily, I'll try fixing this issue.
```
replace (
	go.etcd.io/etcd/api/v3 => go.etcd.io/etcd/api/v3 v3.5.0-alpha.0
	go.etcd.io/etcd/client/pkg/v3 => go.etcd.io/etcd/pkg/v3 v3.5.0-alpha.0
	go.etcd.io/etcd/client/v3 => go.etcd.io/etcd/client/v3 v3.5.0-alpha.0
)
```

**Comment by xpunch** [comment]
try
```
go get github.com/asim/go-micro/plugins/client/grpc/v4@v4.0.0-20211103025805-c5be9f560cdb
```

**Comment by bootfirst** [comment]
Solved perfectly.
Thanks.
