### ISSUE TITLE
Micro API

### ISSUE THREAD

**Issue by asim** [go-micro/go-micro#2343]
Beyond the CLI the micro api was the most popular part of micro itself. It's still doing over 1B api requests per day, which makes me think having it here as a standalone tool might be valuable. The mistake with micro was to create the fat binary that incorporated everything. If we create a separate cmd/api package that might work better.

**Comment by Caplost** [comment]
go-micro v3 how to use micro api cli as  api gateway？@asim 

gomu act as micro ？

![picture](https://user-images.githubusercontent.com/916463/143386307-0c0fd246-2e25-4f50-845d-61a0cf045cc6.png)

**Comment by asim** [comment]
No this is just a mistake.

**Comment by Caplost** [comment]
Which is the right way to use it，i want to use  api gateway just like go-micro v2.

**Comment by asim** [comment]
Then use v2. Go Micro v3-v4 has no API.

**Comment by Caplost** [comment]
just like  api gateway in v3，it‘s convenient.
