### ISSUE TITLE
[BUG]No status received when calling GRPC service

### ISSUE THREAD

**Issue by marvin-liu-sx** [go-micro/go-micro#2347]
Describe the bug

What are you trying to do?
Call service from nodejs GRPC client

What did you expect to happen?
No error

What happens instead?
Service responded:

{
  "error": "2 UNKNOWN: No status received"
}
How to reproduce the bug:

Create a new micro service from micro command line
micro new order --namespace=com.example --type=srv
Write a nodejs client to call the service or use Bloomrpc
Environment:
Go Version: go version go1.17.3 darwin/amd64

**Comment by nashlibby** [comment]
When will it be fixed?

**Comment by blueapplehe** [comment]
the same problem ,when python grpc call go-micro

**Comment by asim** [comment]
Import the grpc client/server in the plugins directory
