### ISSUE TITLE
[BUG] Error creating a client with CLI

### ISSUE THREAD

**Issue by Dmdv** [go-micro/go-micro#2349]
I was following instruction here:
https://github.com/asim/go-micro/tree/master/cmd/micro

When I tried to run 

```
$ micro new client helloworld
creating client helloworld
cd helloworld-client
make tidy
```

I got this error

```bash
helloworld-client imports
	helloworld/proto: package helloworld/proto is not in GOROOT (/opt/homebrew/Cellar/go/1.17.2/libexec/src/helloworld/proto)
make: *** [update] Error 1
```

**Comment by AuditeMarlow** [comment]
A Go Micro client requires the proto package of an existing service in order to create a client for that service. You'll need to point `pb "helloworld/proto"` in the client's `main.go` file to the actual path of the service's proto package.

**Comment by Dmdv** [comment]
@AuditeMarlow 

This is how I fixed this:

1. In the go.mod file I've changed the import

```go
require (
	go-micro.dev/v4 v4.4.0
	golang.org/x/sys v0.0.0-20211123173158-ef496fb156ab // indirect
	transaction-persistence v0.0.0-00010101000000-000000000000
)

replace transaction-persistence => ../transaction-persistence
```

2. And pointed out where all dependencies are located with `replace`
`transaction-persistence` is the service name
Both client and server are located in the same folder

**Comment by Dmdv** [comment]
@AuditeMarlow The default generate client code won't work because in the helloworld/proto should be go.mod file in the code of server which is located in the service root folder
