### ISSUE TITLE
Endless loop in the service

### ISSUE THREAD

**Issue by Dmdv** [go-micro/go-micro#2351]
Major examples shows just pub/sub or streaming examples.
What would be the best practice to implement endless loop serving requests from MQQT message broker with Micro?

**Comment by xpunch** [comment]
Do you mean MQTT?
You can try mqtt broker plugin.
```
import "github.com/asim/go-micro/plugins/broker/mqtt/v4"
```
[Example](https://github.com/xpunch/go-micro-example/tree/main/v4/mqtt)

**Comment by Dmdv** [comment]
@xpunch Thank you! Great!

What about NATS?
I asked in other topic but no reply yet
I couldn't find default Message Broker, how to setup NATS as a default and how to boostrap NATS server with default streams and topics. I know NATS documentation but would like to know how this works with **go-micro**

**Comment by xpunch** [comment]
Have you try the [nats plugin](https://github.com/asim/go-micro/tree/master/plugins/broker/nats)?
It has the same usage as other broker plugins.

**Comment by Dmdv** [comment]
Yes, I've seen it. @xpunch 
My question is rather about this example: 
https://github.com/asim/go-micro/tree/master/examples/broker

It doesn't have any specifics about what kind of broker it uses.

**Comment by xpunch** [comment]
I think that example is just showing how to work with go-micro broker.
Broker is an abstract interface for synchronous communication, it has a default implementation, and you can also replace it by import broker plugins.
For example, if you want to use mqtt broker, you can import it in your codes, and pass it though cli or env.
```
import _ "github.com/asim/go-micro/plugins/broker/mqtt/v4"
```
```
go run . --broker mqtt --broker_address 127.0.0.1:1883
```

**Comment by xpunch** [comment]
I think this issue can be closed too.
