### ISSUE TITLE
Not able to pass request options in NewRequest method

### ISSUE THREAD

**Issue by ghost** [go-micro/go-micro#2352]
type RequestOptions struct {
	ContentType string
	RequestTimeout  time.Duration
}
var reqOpts RequestOptions
reqOpts.ContentType = "application/json"
reqOpts.RequestTimeout =  time.Second * 10
request := cl.NewRequest(Service, Method, Request, reqOpts)

**Comment by xpunch** [comment]
You can pass the request timeout though call options.
```
client.Call(context.TODO(), request, response, client.WithRequestTimeout(10*time.Second))
```

**Comment by ghost** [comment]
Thank you it worked.
