### ISSUE TITLE
Requirements to deploy in K8S

### ISSUE THREAD

**Issue by Dmdv** [go-micro/go-micro#2355]
I want to deploy services based on Micro in Kuber cluster.
Do we need to install micro in k8S for service discovery?

**Comment by xpunch** [comment]
Which registry are you using? There are different registry plugins, like etcd, kubernetes etc.

**Comment by Dmdv** [comment]
@xpunch I'm using Kubernetes, kubectl

**Comment by xpunch** [comment]
Registry is used for service discovery, you may take a look at this.

**Comment by Dmdv** [comment]
@xpunch The registry, is it something that is already built-in?

For example, if I run Service1 and Service2 in one Kubernetes namespace, will they find each other without micro installation in the Kuber cluster?

**Comment by xpunch** [comment]
The registry plugins is also need to be import in your codes.
I don't understand "micro installation in the cluster"?

**Comment by Dmdv** [comment]
I see. I need to use registry plugin.

What I meant by the micro installation in the cluster:
https://github.com/asim/go-micro/tree/master/cmd/micro
I thought that micro cli serves as a daemon to register services,
because from it's examples I can see that we can list services running locally.

Hence, I thought if it's used to enumerate services then I need to install it in the cluster as a daemon

**Comment by xpunch** [comment]
Yeah, cmd/micro is just an cli tool used to help develop services with go-micro, your services can run independently without cmd/micro.

**Comment by AuditeMarlow** [comment]
You may use the Micro CLI to generate projects with Kubernetes resource files by invoking `micro new service --kubernetes helloworld`. You may also pass the `--skaffold` flag to generate a [Skaffold][1] configuration file, which is used to develop Micro services on Kubernetes.

[1]: https://skaffold.dev/

**Comment by Dmdv** [comment]
I'll close this issue because go-micro has a native support of K8S as a plugin and is configured with `MICRO-REGISTRY` env var
