### ISSUE TITLE
"id":"go.micro.client","code":408,"detail":"context deadline exceeded","status":"Request Timeout"

### ISSUE THREAD

**Issue by sylarj** [go-micro/go-micro#2356]
I have two services: serviceA, serviceB; when serviceA send request to serviceB, it returns {"id":"go.micro.client","code":408,"detail":"context deadline exceeded","status":"Request Timeout"};  and I have checked serviceB, but found no request received from serviceA.

**Comment by xpunch** [comment]
Check the services network, could be service A unable to access service B.

**Comment by bootfirst** [comment]
use **Wireshark** to check the network data

**Comment by sylarj** [comment]
Are there any other possibilities caused this issue ?

**Comment by sylarj** [comment]
no problem with the network

**Comment by JeffreyBool** [comment]
The default context timeout is 5s, see client.go for details 

```go
// DefaultRequestTimeout is the default request timeout
	DefaultRequestTimeout = time.Second * 5
```

Modify the default timeout, generally not recommended to be too long, to find the cause through log burial

It is recommended to check that the context timeout is not set too short when calling upstream
