### ISSUE TITLE
How to add value to metadata?

### ISSUE THREAD

**Issue by seaguest** [go-micro/go-micro#2357]
Hello,

I want to add some value to metadata from grpc method, then process in wrapper, however I found since grpc 1.40, we can't modify the context, the proposed solution is to  use metadata.NewIncomingContext.

https://github.com/grpc/grpc-go/issues/4363

I don't know how to do it in micro?

```
func (s *ServerImpl) Location(ctx context.Context, req *pb.LocationRequest, rsp *pb.City) error {
// add value to context
	md, _ := metadata.FromContext(ctx)
	if md != nil {
		md.Set("tag", "value")
	}
}

func LogWrapper(fn server.HandlerFunc) server.HandlerFunc {
	return func(ctx context.Context, req server.Request, rsp interface{}) error {
 		err := fn(ctx, req, rsp)
 		value, _ := md.Get("tag")  // value is empty
}
}
```

**Comment by xpunch** [comment]
After you modify the metadata, you need to convert back to context, and pass it in your request.

**Comment by seaguest** [comment]
@xpunch 

sorry, I don't get you, could you show me the example code?
in Location method, ctx only exposed Value, Deadline, Done, Err methods, I don't know how to make the modification take effect.

**Comment by xpunch** [comment]
1. 
```
...
ctx, err = metadata.NewContext(ctx, md)
```

2.
```
metadata.Set(ctx, k,v)
```

**Comment by seaguest** [comment]
@xpunch 

This is not working.ctx can't be modified.

As the one mentioned in the issue https://github.com/grpc/grpc-go/issues/4363

```
func (w *wrappedStream) Context() context.Context {
  ctx := w.ServerStream.Context()
  md := metadata.FromIncomingContext(ctx)
  newMD := md.Copy()
  newMD.Append("uuid", id)
  newCtx := metadata.NewIncomingContext(ctx, newMD)
  return newCtx
}

```

However I don't find the proper way to do so.

**Comment by xpunch** [comment]
Sorry, I misunderstand your issue. 
[HandlerWrapper](https://github.com/asim/go-micro/blob/90b3e4af0b58c6fb22833a5f5a08278144e77ae8/plugins/server/grpc/grpc.go#L417)
As the context cannot be modify, and there is no way to pass the context back to previous wrapper, we cannot pass metadata to log wrapper.

**Comment by JeffreyBool** [comment]
You can only try Wrapper wrappers or CallWrappers, for example 

`opentracing.go` 

```go
md, ok := metadata.FromContext(ctx)
	if !ok {
		md = make(metadata.Metadata)
	}

	// Find parent span.
	// First try to get span within current service boundary.
	// If there doesn't exist, try to get it from go-micro metadata(which is cross boundary)
	if parentSpan := opentracing.SpanFromContext(ctx); parentSpan != nil {
		opts = append(opts, opentracing.ChildOf(parentSpan.Context()))
	} else if spanCtx, err := tracer.Extract(opentracing.TextMap, opentracing.TextMapCarrier(md)); err == nil {
		opts = append(opts, opentracing.ChildOf(spanCtx))
	}

	// allocate new map with only one element
	nmd := make(metadata.Metadata, 1)

	sp := tracer.StartSpan(name, opts...)

	if err := sp.Tracer().Inject(sp.Context(), opentracing.TextMap, opentracing.TextMapCarrier(nmd)); err != nil {
		return nil, nil, err
	}

	for k, v := range nmd {
		md.Set(strings.Title(k), v)
	}

	ctx = opentracing.ContextWithSpan(ctx, sp)
	ctx = metadata.NewContext(ctx, md)
```

**Comment by JeffreyBool** [comment]
> Hello,
> 
> I want to add some value to metadata from grpc method, then process in wrapper, however I found since grpc 1.40, we can't modify the context, the proposed solution is to use metadata.NewIncomingContext.
> 
> [grpc/grpc-go#4363](https://github.com/grpc/grpc-go/issues/4363)
> 
> I don't know how to do it in micro?
> 
> ```
> func (s *ServerImpl) Location(ctx context.Context, req *pb.LocationRequest, rsp *pb.City) error {
> // add value to context
> 	md, _ := metadata.FromContext(ctx)
> 	if md != nil {
> 		md.Set("tag", "value")
> 	}
> }
> 
> func LogWrapper(fn server.HandlerFunc) server.HandlerFunc {
> 	return func(ctx context.Context, req server.Request, rsp interface{}) error {
>  		err := fn(ctx, req, rsp)
>  		value, _ := md.Get("tag")  // value is empty
> }
> }
> ```

Write two functions that implement `server.HandlerWrapper`, the first `server.HandlerWrapper` does md.set, then saves the modified md to the new `context`, then the second `server.HandlerWrapper` goes and gets the `context`'s md value.

**Comment by JeffreyBool** [comment]
> Sorry, I misunderstand your issue. [HandlerWrapper](https://github.com/asim/go-micro/blob/90b3e4af0b58c6fb22833a5f5a08278144e77ae8/plugins/server/grpc/grpc.go#L417) As the context cannot be modify, and there is no way to pass the context back to previous wrapper, we cannot pass metadata to log wrapper.

先走 grpc  拦截器，拦截到东西，处理完了，然后走 micro handler 方法，但是没法在 grpc server 方法修改 context  啊，我能想到的都是 gprc前置拦截, 然后micro  HandlerWrapper 获取可以继续干啥，你有啥思路吗

**Comment by seaguest** [comment]
@JeffreyBool 

根据grpc最新的设计，outbound的context修改必须用metadata.NewIncomingContext，所以只能从micro框架内部做相应的修改，如果你选择grpc1.38.0，你会发现简单的set，get依然还是可以的。

我的需求很简单，本想统一处理错误码（读取response的code），现在只能通过json解析response了。
等待micro出一个官方的方案吧。

**Comment by JeffreyBool** [comment]
> 想统一处理错误码

啥错误吗？grpc 调用出错处理吗

**Comment by seaguest** [comment]
@JeffreyBool 
业务层级的错误码，譬如response都有的固定结构，err_code, err_msg这样的。
既然context没法修改，可以尝试在rsp interface{}里面增加对应的临时字段，当然这个只是没有办法的办法。

**Comment by JeffreyBool** [comment]
> @JeffreyBool 业务层级的错误码，譬如response都有的固定结构，err_code, err_msg这样的。 既然context没法修改，可以尝试在rsp interface{}里面增加对应的临时字段，当然这个只是没有办法的办法。

```go
type monWrapper struct {
	client.Client
}

// NewClientWrapper  monitor returns a Client Wrapper
func NewClientWrapper() client.Wrapper {
	return func(c client.Client) client.Client {
		return &monWrapper{c}
	}
}

func parseMetricMethodName(path string) string {
	return strings.Trim(strings.Replace(path, "/", ".", -1), ".")
}

func (o *monWrapper) Call(ctx context.Context, req client.Request, rsp interface{}, opts ...client.CallOption) error {
	startTime := time.Now()

	err := o.Client.Call(ctx, req, rsp, opts...)

	businessCode := errors.ConvertBusinessCode(err)
	methodName := parseMetricMethodName(req.Method())
	name := fmt.Sprintf("GrpcClient.%s.%s", req.Service(), methodName)

	monitorHandler := func(name string, businessCode int) {
		code := businessCode
		monitor.DefaultMetrics.Timer(name, startTime, monitor.TagCode, code, monitor.TagClient, "grpc")
	}

	defer monitorHandler(name, businessCode)

	if err != nil {
		return err
	}

	return nil
}

func (o *monWrapper) Stream(ctx context.Context, req client.Request, opts ...client.CallOption) (client.Stream, error) {
	return o.Client.Stream(ctx, req, opts...)
}

func (o *monWrapper) Publish(ctx context.Context, p client.Message, opts ...client.PublishOption) error {
	startTime := time.Now()

	err := o.Client.Publish(ctx, p, opts...)

	businessCode := errors.ConvertBusinessCode(err)
	name := fmt.Sprintf("BrokerPublish.%s", p.Topic())

	monitorHandler := func(name string, businessCode int) {
		code := businessCode
		monitor.DefaultMetrics.Timer(name, startTime, monitor.TagCode, code)
	}

	defer monitorHandler(name, businessCode)

	if err := o.Client.Publish(ctx, p, opts...); err != nil {
		return nil
	}

	return nil
}

// NewHandlerWrapper accepts an opentracing Tracer and returns a Handler Wrapper
func NewHandlerWrapper() server.HandlerWrapper {
	return func(h server.HandlerFunc) server.HandlerFunc {
		return func(ctx context.Context, req server.Request, rsp interface{}) error {
			start := time.Now()
			err := h(ctx, req, rsp)
			businessCode := errors.ConvertBusinessCode(err)

			name := fmt.Sprintf("GrpcServer.%s.%s", req.Service(), parseMetricMethodName(req.Method()))

			monitorHandler := func(name string, businessCode int) {
				code := businessCode
				monitor.DefaultMetrics.Timer(name, start, monitor.TagCode, code, monitor.TagServer, "grpc")
			}

			defer monitorHandler(name, businessCode)

			if err != nil {
				return err
			}

			return nil
		}
	}
}

```

```go
const (
	Success             = 0
	ChannelBroken       = 9
	FailedPrecondition  = 100
	Unavailable         = 101
	Canceled            = 102
	DeadlineExceeded    = 103
	BadRequest          = 400
	Unauthorized        = 401
	Forbidden           = 403
	NotFound            = 404
	MethodNotAllowed    = 405
	Timeout             = 408
	Conflict            = 409
	InternalServerError = 500
	UnKnown             = 1001
)

func ConvertBusinessCode(err error) int {
	code := InternalServerError
	switch err.(type) {
	case nil:
		code = Success
	case *url.Error:
		code = Unavailable

	case *mErrors.Error:
		v := err.(*mErrors.Error)
		code = int(v.Code)
		// go-micro 的 code 小于 BadRequest 统一改成 InternalServer
		if code < BadRequest {
			code = InternalServerError
		}
	default:
		switch err {
		case io.EOF:
			code = ChannelBroken
		case io.ErrClosedPipe, io.ErrNoProgress, io.ErrShortBuffer, io.ErrShortWrite, io.ErrUnexpectedEOF:
			code = FailedPrecondition
		case context.DeadlineExceeded:
			code = DeadlineExceeded
		case context.Canceled:
			code = Canceled
		}
	}
	return code
}

// IsErrorCodeEqual 判断错误码是否相等
func IsErrorCodeEqual(err, target error) bool {
	return ConvertBusinessCode(err) == ConvertBusinessCode(target)
}

```

你要的应该就是上面的代码吧？

**Comment by seaguest** [comment]
@JeffreyBool 
的确我也正在做接口监控统计的事情，目前遇到的问题是我可以在wrapper里面检测到错误码（err），业务层次的错误码（rsp提取），但是我没办法在wrapper里面上报到influxdb。

我看你用的是monitor.DefaultMetrics（应该是默认的配置吧，我希望能够自定义），如果希望传个对象给wrapper（比如处理上报influxdb的逻辑），有没有办法实现？如果context能存对象，这个就很方便了。

**Comment by JeffreyBool** [comment]
> @JeffreyBool 的确我也正在做接口监控统计的事情，目前遇到的问题是我可以在wrapper里面检测到错误码（err），业务层次的错误码（rsp提取），但是我没办法在wrapper里面上报到influxdb。
> 
> 我看你用的是monitor.DefaultMetrics（应该是默认的配置吧，我希望能够自定义），如果希望传个对象给wrapper（比如处理上报influxdb的逻辑），有没有办法实现？如果context能存对象，这个就很方便了。

解析 error 信息不就行了吗？你研究一下 errors 的定义，正常来说监控的话 err != nil 都是出错，然后把错误码捕获就行了，我上面的代码已经贴了怎么捕获错误码转换成自己对应的错误码

**Comment by JeffreyBool** [comment]
> 既然context没法

指标捕获不建议捕获 response  返回，那是业务的返回，结构不固定，正常来说是扩展 errors 来做

**Comment by seaguest** [comment]
@JeffreyBool 
想了一圈，发现还是你的这个接口监控，错误方案比较靠谱。
对了，NewClientWrapper这个怎么使用，似乎client.Wrapper用法说明比较少，我下面这么用server.HandlerWrapper是可以的，但是NewClientWrapper没反应。

```

	service := micro.NewService(
		micro.Name(constant.UtilServiceName),
		micro.Version("latest"),
		micro.RegisterTTL(time.Second*30),
		micro.RegisterInterval(time.Second*15),
		micro.Server(grpc.NewServer(server.Address(""), server.Name(constant.UtilServiceName))),
		micro.Registry(reg),
		micro.WrapHandler(NewHandlerWrapper()),
		micro.WrapClient(NewClientWrapper()),
	)

```
