### ISSUE TITLE
[FEATURE] Dashboard

### ISSUE THREAD

**Issue by xpunch** [go-micro/go-micro#2359]
It is easy to build a micro service system base on go micro, but we can't see the inner structure in the system. So I created a [go micro dashboard](https://github.com/xpunch/go-micro-dashboard), which can be used to see all go micro services under registry. It can also used to mock client requests.

**Comment by xpunch** [comment]
![dashboard](https://user-images.githubusercontent.com/5229945/142965333-6908c41b-72ba-4a70-8114-de082bba1433.png)

**Comment by xpunch** [comment]
View all services
![services](https://user-images.githubusercontent.com/5229945/142965349-969242b3-61a8-4001-bffe-38ff1609d4a0.png)

**Comment by xpunch** [comment]
View service detail
![service](https://user-images.githubusercontent.com/5229945/142965386-cad129ca-4f01-44b8-9586-75cfc95996c4.png)

**Comment by xpunch** [comment]
Mock client call
![call](https://user-images.githubusercontent.com/5229945/142965406-6871089b-25d2-40af-b6a3-fc63ffc40688.png)

**Comment by asim** [comment]
Nice. I think we'd welcome that either in the repo as go-micro/cmd/dashboard or just a helpful link to it.

**Comment by xpunch** [comment]
OK, I'll create a copy into cmd/dashboard without the web project.
