### ISSUE TITLE
[BUG] Missing port in address

### ISSUE THREAD

**Issue by Dmdv** [go-micro/go-micro#2360]
I was following instructions from here:
https://github.com/asim/go-micro/tree/master/cmd/micro

1. Create a server
2. Generated server client
3. After trying to run the client:

```shell
2021-11-23 23:49:11  file=transaction-persistence-client/main.go:30 level=fatal {"id":"go.micro.client","code":500,"detail":"connection error: dial tcp: address [[fd55:e0da:f8c9:3:cd7:c048:5b48:a505]]:64083: missing port in address","status":"Internal Server Error"}
exit status 1
```

This is the client code:

```go
func main() {
	// Create service
	srv := micro.NewService()
	srv.Init()

	// Create client
	c := pb.NewTransactionPersistenceService(service, srv.Client())

	for {
		// Call service
		rsp, err := c.Call(context.Background(), &pb.CallRequest{Name: "John"})
		if err != nil {
			log.Fatal(err)
		}

		log.Info(rsp)

		time.Sleep(1 * time.Second)
	}
}

```

**Comment by Dmdv** [comment]
Documents are definitely out of sync with the current state.
To my view, what is missing here, it's how to start the server and client using default transport and default service discovery when you run locally and run in the cluster

**Comment by asim** [comment]
You've got an ipv6 address, there's known issues with that. Someone like @xpunch may be able to help.

**Comment by Dmdv** [comment]
I'll close it as it is no more relevant.
Issues was not connected to the code itself and discontinued to reproduce

**Comment by epolar** [comment]
I face the same issue. I resolve it by hard code address:
```go
	// Create service
	srv := micro.NewService(
		micro.Name(service),
		micro.Version(version),
		micro.Address("127.0.0.1:8000"),
	)
	srv.Init()
```

System: macOS Big Sur  11.6
Go version: go version go1.17.5 darwin/amd64
micro --version: micro version latest
protoc-gen-go --version: protoc-gen-go v1.27.1
protoc --version: libprotoc 3.19.4
