### ISSUE TITLE
Hello world example can not create micro service

### ISSUE THREAD

**Issue by h1z3y3** [go-micro/go-micro#2362]
I use [micro](https://github.com/micro/micro) to run `helloworld` example [here](https://github.com/asim/go-micro/tree/master/examples/helloworld),  after `micro run`, I can't find the service in `micro service` but the service is in `micro status`.

![image](https://user-images.githubusercontent.com/12080364/143249056-0d15a8f8-00a6-40b8-a7c1-48942eb771be.png)

BTW, if I run `helloworld` example in the [micro repo](https://github.com/micro/services/tree/master/helloworld), there is no problem. The `helloworld-in-micro` service can find in the result list.

![image](https://user-images.githubusercontent.com/12080364/143248519-abc36298-88da-4113-a08f-9811de13f5b3.png)

**Comment by asim** [comment]
You are confusing too different tools. Go Micro is not compatible with Micro. These are two different tools.

**Comment by asim** [comment]
If you want to run go-micro services with micro it needs to use the service registry which exists in github.com/micro/micro/v3/service/registry/client

**Comment by h1z3y3** [comment]
Thanks for your reply. 
What confuses me is that it shows me using 'micro' to run the service [here](https://github.com/asim/go-micro/tree/master/examples/helloworld) 🤣

**Comment by h1z3y3** [comment]
Oh my god! 
How stupid am I!

The 'micro' tool in the readme is [THIS MICRO](https://github.com/asim/go-micro/tree/master/cmd/micro)

Please forgive my ignorance! 🥲
