### ISSUE TITLE
docker-compose trouble

### ISSUE THREAD

**Issue by charles-hashdak** [go-micro/go-micro#2365]
Hello everyone! 
(Please excuse my english in advance, I will try to do my best to be as clear as I can)

I am really stuck on trying to launch my micro services with go-micro v3 with docker-compose...
I made it work with go-micro v2 but without docker-compose and I had several issues, that's why I want to move to v3.
But for now, I keep having issues and the one that keeps coming back is : 
`2021-11-26 20:39:31  file=cmd/cmd.go:434 level=fatal Error setting up auth: {"Id":"go.micro.client","Code":500,"Detail":"{\"Id\":\"go.micro.client\",\"Code\":500,\"Detail\":\"service auth: route not found\",\"Status\":\"Internal Server Error\"}","Status":"Internal Server Error"}`

My docker-compose.yml file is the following (I tried a lot of other solutions but this is the last one I tried with the issue):
```# docker-compose.yml
version: '3.5'
services:
  catalog:
    container_name: catalog
    restart: always
    build: ./catalog-service
    environment:
      MICRO_REGISTRY_ADDRESS: "micro:8000"
      MICRO_BROKER_ADDRESS: "micro:8003"
  micro:
    image: micro/micro
    command: ["server"]
    container_name: micro
````

I am successfully logged in when I do : `sudo docker exec -it micro ./micro login --username=admin --password=micro`

And this is the logs from `sudo docker-compose up micro`:
```
micro            | 2021-11-26 19:58:50  file=user/user.go:99 level=info Setting up keys for JWT at /root/.micro/id_rsa and /root/.micro/id_rsa.pub
micro            | 2021-11-26 19:58:51  file=server/server.go:88 level=info Starting server
micro            | 2021-11-26 19:58:51  file=server/server.go:116 level=info Registering registry
micro            | 2021-11-26 19:58:51  file=server/server.go:116 level=info Registering broker
micro            | 2021-11-26 19:58:51  file=server/server.go:116 level=info Registering network
micro            | 2021-11-26 19:58:51  file=server/server.go:116 level=info Registering runtime
micro            | 2021-11-26 19:58:51  file=server/server.go:116 level=info Registering config
micro            | 2021-11-26 19:58:51  file=server/server.go:116 level=info Registering store
micro            | 2021-11-26 19:58:52  file=server/server.go:116 level=info Registering events
micro            | 2021-11-26 19:58:52  file=server/server.go:116 level=info Registering auth
micro            | 2021-11-26 19:58:52  file=server/server.go:116 level=info Registering proxy
micro            | 2021-11-26 19:58:52  file=server/server.go:116 level=info Registering api
micro            | 2021-11-26 19:58:52  file=server/server.go:116 level=info Registering web
micro            | 2021-11-26 19:58:52  file=server/server.go:206 level=info Starting server runtime
```

The goal would be to reproduce the use I have with the v2 using the /rpc endpoint of go-micro api as a gateway to my microservices (I have 4-5 others like the catalog one).

Thank you very much for reading me, I would be very greatful if anyone can help me!
(Let me know if you need more informations)

**Comment by xpunch** [comment]
The micro is not works with go-micro, maybe you need to build your own micro docker image with 1.9.1.

**Comment by asim** [comment]
Micro and go-micro split at v3. Technically you can use them together but you'd need to define and load the plugins for micro in your go-micro service. The minimum requirement would be grpc client/server and the same registry.

**Comment by asim** [comment]
My advice would be to see the divergence as two now non compatible pieces of software with different goals. Micro has an upgrade guide on the site if you want to keep going with that tool otherwise there's a huge ecosystem around the plugins go-micro supports.

**Comment by charles-hashdak** [comment]
Oh ok my bad! 
Thank you very much for the response!

**Comment by andrew-jones** [comment]
What version of micro should we be building images with for go-micro v4?  1.9.1 is pretty old, I'm using 1.16.0 and want to upgrade golang among other things.  v2.9.3?  It looks like the last tag before v3.  Is there a fork for micro supporting go-micro?
