### ISSUE TITLE
go1.17 problem

### ISSUE THREAD

**Issue by wnz27** [go-micro/go-micro#2367]
when i use `go mod tidy` but:
```shell
go mod tidy: go.mod file indicates go 1.17, but maximum supported version is 1.16
```

**Comment by wnz27** [comment]
but i fix go.mod's `go 1.17` to `go 1.16` i can use `go mod tidy` success.

**Comment by xpunch** [comment]
You are using go 1.16, so upgrade your golang version may fix your issue.

**Comment by xpunch** [comment]
Many go open source projects support latest two versions of golang, should we follow that rule too?

**Comment by asim** [comment]
Likely but I'm not sure if go modules supports defining two.

**Comment by xpunch** [comment]
[Release Policy](https://go.dev/doc/devel/release#policy)
> Each major Go release is supported until there are two newer major releases. For example, Go 1.5 was supported until the Go 1.7 release, and Go 1.6 was supported until the Go 1.8 release. We fix critical problems, including critical security problems, in supported releases as needed by issuing minor revisions (for example, Go 1.6.1, Go 1.6.2, and so on).

Maybe we should not upgrade go version in go.mod so frequently, if go-micro works fine with go 1.15, there is no need to upgrade to 1.17. Users who still develop in lower go versions may unable to use latest go-micro.

**Comment by asim** [comment]
We'll keep it in mind for future versions then

**Comment by wnz27** [comment]
> You are using go 1.16, so upgrade your golang version may fix your issue.

I use go 1.17 cause the first I said error

**Comment by xpunch** [comment]
Try
`
go mod tidy -go=1.16 && go mod tidy -go=1.17
`

**Comment by wnz27** [comment]
> Try `go mod tidy -go=1.16 && go mod tidy -go=1.17`

i try it success but i can't understand this cmd mean , can u explain it simply

**Comment by xpunch** [comment]
Could be a dependency issue, some imported package still under go 1.16, but their dependencies were upgraded to go 1.17.

**Comment by wnz27** [comment]
> Could be a dependency issue, some imported package still under go 1.16, but their dependencies were upgraded to go 1.17.

thank you explain~
