### ISSUE TITLE
How can i fixed this issue?

### ISSUE THREAD

**Issue by stiffer831** [go-micro/go-micro#2376]
![image](https://user-images.githubusercontent.com/23020938/144652395-2f8c1592-7b04-43bc-95ef-2dc10a9a6467.png)

**Comment by JeffreyBool** [comment]
> ![image](https://user-images.githubusercontent.com/23020938/144652395-2f8c1592-7b04-43bc-95ef-2dc10a9a6467.png)

```shell
$ go install github.com/asim/go-micro/cmd/protoc-gen-micro/v4@latest
```

**Comment by xpunch** [comment]
```
go install go-micro.dev/v4/cmd/protoc-gen-micro@v4
```

**Comment by stiffer831** [comment]
> ```shell
> go install github.com/asim/go-micro/cmd/protoc-gen-micro/v4@latest
> ```

Thanks!

**Comment by stiffer831** [comment]
> ```
> go install go-micro.dev/v4/cmd/protoc-gen-micro@v4
> ```

Thanks!
