### ISSUE TITLE
Confused about performance test results

### ISSUE THREAD

**Issue by EnigmaOppo** [go-micro/go-micro#2387]
Recently, I was performing performance testing on the go-micro framework. During the testing, I found that the performance was very low. Below is some information about my testing.

**Container Specification**：4C8G，10000Mb/s

**code of server**：
```
type OrderServer struct {
}

var count int64 = 0

func (s *OrderServer) Echo(ctx context.Context, req *OrderService.RequestString, rp *OrderService.ResponseString) error {
	rp.Response = req.Request
	atomic.AddInt64(&count, 1)
	return nil
}

func main() {
	consulRegister := consul.NewRegistry(func(options *registry.Options) {
		options.Addrs = []string{
			"xxx.xxx.xxx.xxx:8500",
		}
	})

	service := micro.NewService(
		micro.Name("xxx"),
		micro.Registry(consulRegister),
		micro.Address(":9999"),
		micro.Transport(grpc.NewTransport()),
	)
	service.Init()
	err := OrderService.RegisterOrderServiceHandler(service.Server(), new(OrderServer))
	if err != nil {
		return
	}
	go func() {
		ticker := time.NewTicker(5 * time.Second)
		for {
			select {
			case <-ticker.C:
				logger.Info("tps:", count/5)
				atomic.StoreInt64(&count, 0)
			}
		}
	}()

	err = service.Run()
	if err != nil {
		os.Exit(-1)
	}
}
```
**plugins:**
- registry : consul
- client/server: rpc
- transport:grpc

For comparison, I tested GRPC and Dubbo-go at the same time, the following is the test result:
![image](https://user-images.githubusercontent.com/83863252/146334492-d39e10ef-c156-46bb-b6f4-47e06dfc6379.png)

**version of each framework:**
- go-micro: v3.7.0
- Dubbo-go: v3.0.0
- GRPC: v1.38.0

As can be seen from the figure, the performance of go-micro is much lower than Dubbo-go and GRPC, I tried to find the reason and used pprof to analyze the performance of GRPC and go-micro. The following is a comparison of the two flame graphs:
![image](https://user-images.githubusercontent.com/83863252/146332572-0ba2a5d4-ad4c-4933-983f-52daab9fefcb.png)
<center>flame graph of go-micro</center>

![image](https://user-images.githubusercontent.com/83863252/146332752-5543dcba-12a8-4553-a367-901e418b2e98.png)
<center>flame graph of GRPC</center>

We can see that go-micro spends most of its time sending and receiving data, and the same is true for GRPC. But why is the performance of go-micro so much lower than GRPC?

Does anyone know the reason? Or is my test itself problematic?

Please help me find out where the problem is, thank you very much!

**Comment by asim** [comment]
Grpc accepts an ipv4 address or DNS name. There is no service discovery. Because go-micro provides service discovery every request must first be looked up. To avoid this you need to enable some form of registry caching via an appropriate selector. Otherwise the bottleneck is consul.

**Comment by asim** [comment]
The other thing to note. Your configuration is suboptimal. You're using the RPC client/server with grpc transport whereas what you want to use is the grpc client/server plugins in the plugins repo. Then you'll likely see comparable benchmarks to grpc itself.

**Comment by EnigmaOppo** [comment]
> The other thing to note. Your configuration is suboptimal. You're using the RPC client/server with grpc transport whereas what you want to use is the grpc client/server plugins in the plugins repo. Then you'll likely see comparable benchmarks to grpc itself.

Okay, as far as I know, the consul registry itself is cached. I try to replace the client and server with GRPC. Thank you so much.

**Comment by EnigmaOppo** [comment]
> The other thing to note. Your configuration is suboptimal. You're using the RPC client/server with grpc transport whereas what you want to use is the grpc client/server plugins in the plugins repo. Then you'll likely see comparable benchmarks to grpc itself.

I tried to replace the client and server of RPC with GRPC client and server and found that the performance has increased sharply, and the performance has surpassed Dubbo-go. Here are the latest test results:
![image](https://user-images.githubusercontent.com/83863252/146483919-c8b2ef56-805b-4e02-89d8-e7e5c369e191.png)
And this is the latest frame graph
![image](https://user-images.githubusercontent.com/83863252/146484005-cea2f8c6-9545-4a7e-8fef-85ff76b8a3ab.png)
@asim Thank you very much for your suggestion, it helped me a lot.

**Comment by xpunch** [comment]
Use cached registry or specific server addresses can improve service discovery performance too.

[CachedRegistry](https://github.com/asim/go-micro/tree/master/registry/cache)
```
micro.NewService(micro.Registry(cache.New(consulRegister)))
```

[CallOptions](https://github.com/asim/go-micro/blob/37de747d195c32bd2deaea06d0064bf5e2c89cfa/client/options.go#L50)
```go
orderService.Echo(ctx, req, client.WithAddress("xxx.xxx.xxx.xxx:9999"))
```

**Comment by asim** [comment]
Yes the key thing to note, even with a cached registry, a lookup must still be performed from the cache. It will never be possible to have a like for like comparison with others. Go Micro is a higher level framework, gRPC in itself is a protocol and their framework is quite low level.

**Comment by EnigmaOppo** [comment]
> Use cached registry or specific server addresses can improve service discovery performance too.
> 
> [CachedRegistry](https://github.com/asim/go-micro/tree/master/registry/cache)
> 
> ```
> micro.NewService(micro.Registry(cache.New(consulRegister)))
> ```
> 
> [CallOptions](https://github.com/asim/go-micro/blob/37de747d195c32bd2deaea06d0064bf5e2c89cfa/client/options.go#L50)
> 
> ```go
> orderService.Echo(ctx, req, client.WithAddress("xxx.xxx.xxx.xxx:9999"))
> ```

Thank you very much for your suggestion, I will try it.

**Comment by asim** [comment]
If your test calls for a fixed address then you should use call WithAddress as otherwise it's not a fair comparison

**Comment by EnigmaOppo** [comment]
> Yes the key thing to note, even with a cached registry, a lookup must still be performed from the cache. It will never be possible to have a like for like comparison with others. Go Micro is a higher level framework, gRPC in itself is a protocol and their framework is quite low level.

You are right, I know that go-micro is a higher-level framework, but I want to know where the limits of go-micro are, which will facilitate my subsequent frame selection. Now it seems that go-micro is great and very convenient to use. Thank you for your development of the go-micro framework. Your works are so cool.

**Comment by EnigmaOppo** [comment]
> If your test calls for a fixed address then you should use call WithAddress as otherwise it's not a fair comparison

I‘ll try it.

**Comment by Davincible** [comment]
@EnigmaOppo how did you end up setting up your services for optimal performance? I'd like to learn!
