### ISSUE TITLE
[BUG]python grpc call go-micro err：StatusCode.UNKNOWN

### ISSUE THREAD

**Issue by blueapplehe** [go-micro/go-micro#2390]
**Describe the bug**

1. What are you trying to do?
2. What did you expect to happen?
3. What happens instead?

**How to reproduce the bug:**

If possible, please include a minimal code snippet here.

**Environment:**
Go Version: please paste `go version` output here
```
please paste `go env` output here
```

**Comment by xpunch** [comment]
Duplicate with #2347.
