### ISSUE TITLE
the sql query become slowed

### ISSUE THREAD

**Issue by stopter** [go-micro/go-micro#2393]
i use go-micro write three servers gateway,upload,policy
and threes servers and mysql are deploy on the same centos
in policy sever,there is a sql :select * from store where oid = 2 limit 1,the table store have only two rows,the time quey this sql is 300us~2ms,i think this is normal
when upload server is busy,do sql frequently(cpu can be 150%),and rpc request policy server to do this sql,
loop this every 5 minute,the time query this sql become more big,2ms,3ms,....10ms ,20ms...,even 1s
i do not know why,because ,the upload is busy,but not always busy,and Most of the time  is  not busy,
the time can not be recoverd even i stop the upload
can you give me some suggestion?
think you very much

**Comment by xpunch** [comment]
I don't think this is issue of go micro, check your mysql server or go client package.
