### ISSUE TITLE
Switch default content type to json

### ISSUE THREAD

**Issue by asim** [go-micro/go-micro#2404]
I want to move the default rpc client/server away from protobuf and code generation to using JSON by default. This will allow any Go type to be marshaled without having to deal with proto. 

This should not affect grpc plugins as they should have their own defaults. What this allows is clean movement of Go Micro into the next phase of its life.

**Comment by xpunch** [comment]
So we need another tool help register handlers, or just leave it to developers?

**Comment by asim** [comment]
Why would we need a tool to help register handlers? The server has a Register method.

**Comment by xpunch** [comment]
Developers will need to write those codes which generated by protoc-gen-micro currently, not only register handlers by server, but also wrap call requests by client. There are some other rpc frameworks use custom scaffold to generate service and models by custom definitions. Change from protobuf to JSON is ok, maybe we'll need a solution to replace protoc-gen-micro?

**Comment by asim** [comment]
I don't want to duplicate scaffolding right now. What I want to do is enable the client/server usage without protobuf. Meaning a user defines request/response types themselves or quite simply passes in generic Go types. 

You can quite simply do the following in the client:

```go
request := client.NewRequest("greeter", "Greeter.Hello", "john", client.WithContentType("application/json"))

var response string

if err := client.Call(context.TODO(), request, &response); err != nil {
	fmt.Println(err)
}
```

And in the server:

```go
type Greeter struct{}

func (g *Greeter) Hello(ctx context.Context, name *string, msg *string) error {
	*msg = "Hello " + *name
	return nil
}
```

Handler registered like so

```go
micro.RegisterHandler(service.Server(), new(Greeter))
```

Basically you can use pointers to any Go types, but it requires the client to specify application/json as the content-type. For the rpc client I would like to default it to that. Or perhaps detect by doing:

```go
func NewRequest(service, endpoint string, request interface{}) Request {
   if _, ok := request.(proto.Message); !ok {
      contentType := "application/json"
   }
   ...
}
```
