### ISSUE TITLE
How to implement tracing with opentelemetry

### ISSUE THREAD

**Issue by FarhanSajid1** [go-micro/go-micro#2405]
I've been trying to get tracing working with `openTelemetry`, the basic setup is as follows:
gateway -> grpc -> service

I am able to get 2 individual traces, 1 for the gateway and 1 for the service, but this should really be 1 span that can be broken into two. 

Using Chi Router I should be able to do this
```
func (mw TracingMiddleware) Wrap(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		rt, _ := router.CurrentRoute(r)
		ctx, span := mw.Tracer.Start(r.Context(), r.Method + " " + rt.Route, trace.WithSpanKind(trace.SpanKindServer))
		r = r.WithContext(ctx)
		defer span.End()
		next.ServeHTTP(w, r)
	})
}

```

This should add a span to the context, and I can verify this happens by inspecting the context in debug mode.

However, when I pass the context to the go micro grpc endpoint, the span is lost, and instead the context contains these
```
micro-span-id -> 9d9bd6a0-4346-45cb-857d-a7362d1729c6
Micro-Trace-Id -> b1665b37-a529-4e6a-98db-c1b449eafa16
```

How should I implement this?

**Comment by refs** [comment]
You should serialize the trace in the context for another service to continue adding spans on it. I did some work on it that you can peek [here](https://github.com/owncloud/ocis/blob/master/ocis-pkg/tracing/tracing.go#L15-L19) Essentially all services have to be on the same page on which propagation strategy to use, so the trace can be reconstructed. The rest is up to the OT interceptors.

**Comment by FarhanSajid1** [comment]
@refs so you didn’t use the existing middleware? And instead attached the baggage to the trace and pass that around? 

Do you have a simple example of this? I’ll look at the example you provided

**Comment by xpunch** [comment]
https://github.com/go-micro/plugins/tree/main/v4/wrapper/trace/opentelemetry
