### ISSUE TITLE
Still accepting maintainers?

### ISSUE THREAD

**Issue by refs** [go-micro/go-micro#2413]
Having a look at #2313 I was wondering if that's still the case :) I use go-micro on my home lab as well at heavily here at ownCloud oCIS project, so we're pretty much showered on it, and I'm willing to lend my time to the project, if that's still the case.

**Comment by asim** [comment]
Yea happy to accept you as a maintainer. Key points would be; open discussions or issues for any new work, get one other person to OK it, and then open a PR.

**Comment by asim** [comment]
You've now been added
