### ISSUE TITLE
Add bash completion

### ISSUE THREAD

**Issue by mmatczuk** [go-micro/go-micro#2432]
It would be very handy if the micro command provided bash completion.
In my view the best would be to adopt the `echo 'source <(micro completion bash)' >>~/.bashrc` technique [2].

It looks like the library being used supports automatic generation of completion for bash, zsh and others [1].

[1] https://github.com/urfave/cli/blob/master/docs/v2/manual.md#bash-completion
[2] https://kubernetes.io/docs/tasks/tools/included/optional-kubectl-configs-bash-linux/#bash

**Comment by Davincible** [comment]
Thanks for providing the links. 

The CLI has been moved over to https://github.com/go-micro/cli

Just added auto completion there.

```bash
source <(go-micro completion bash)
```
