### ISSUE TITLE
{"id":"go.micro.client","code":503,"detail":"connection closed","status":"Service Unavailable"}

### ISSUE THREAD

**Issue by XuJingChao1** [go-micro/go-micro#2434]
Before asking, please check if your question has already been answered: 

1. Check the documentation - https://micro.mu/docs/
2. Check the examples and plugins - https://github.com/micro/examples & https://github.com/micro/go-plugins
3. Search existing issues

**Comment by clement2026** [comment]
@XuJingChao1 
To help us figure out what's going on, please provide more details. We recommend using the following template:

## Describe the bug

1. What are you trying to do?
2. What did you expect to happen?
3. What happens instead?

## How to reproduce the bug

If possible, please include a minimal code snippet here.

## Environment

Go Version: please paste `go version` output here

```go
please paste `go env` output here
```
