### ISSUE TITLE
Distributed Transaction support

### ISSUE THREAD

**Issue by yedf2** [go-micro/go-micro#2442]
Hi, I am the author of dtm-labs/dtm, a distributed transaction framework. I want to support go-micro. 

If go-micro distributed transaction is supported by DTM, DTM will also add a link to go-micro. Can you add an item in README‘s feature and link to DTM? 

It helps much to both go-micro and DTM users.
@asim

**Comment by asim** [comment]
We don't currently support DTM. I'd need to look at the project to understand which way the integration would work. Whether we'd define an interface and plugin or DTM makes use of go-micro. In any case we're not really in the habit of adding things to the readme for crosslinking. If there's an integration you'd like to add we're happy to look at it.

**Comment by yedf2** [comment]
why not cross-linking in readme? It is convenient for user to access things interested and many repos do this: go-kit/kit alibaba/nacos.

Currently DTM have support polarismesh/polaris,  zeromicro/go-zero. These repos only need to export its register/discover interface to public, and DTM will do the integration.

**Comment by asim** [comment]
I would link to something I personally use or support. I have not used DTM and don't know what an integration looks like so it's not useful or honest for me to do this. DTM might be a great framework but I don't personally know that. We haven't selectively picked favourites here. We create abstractions for complex distributed systems problems for developers and provide plugins for external systems for that.

**Comment by yedf2** [comment]
Of course you should not link to DTM before you know DTM. So can you have a look at DTM, and make an evaluation?

Distributed transaction is somehow very important to micro-services. Listing it in features not in plugins is a common case.

**Comment by asim** [comment]
There's a prior attempt at an interface for this now in a fork https://github.com/unistack-org/micro/blob/master/flow/flow.go. if we were to add anything we'd have to look at distributed transactions in general along with other tools like temporal and decide what to do. 

I'll have a look when I have time or ask the other maintainers to look also.

**Comment by yedf2** [comment]
I have study about temporal, and found that it is a workflow engine.
The difference is that: Temporal only ensure all branches of a distributed transaction are executed even in case of temporary failure; but DTM go much further in distributed transaction, it support many patterns for distributed transaction, including Saga, Tcc, XA, and OutBox, support orchestrating Mysql, Postgres, Mongo, Redis to composite a global transaction, and also provide utilities to make compensation, idempotency much more easier.

**Comment by comerc** [comment]
I need Distributed Transaction support with example in https://github.com/go-micro/demo

**Comment by asim** [comment]
You can ask @vtolstov if he wants to contribute his interface back and implement in the demo

**Comment by comerc** [comment]
> The difference is that: Temporal only ensure all branches of a distributed transaction are executed even in case of temporary failure; but DTM go much further in distributed transaction, it support many patterns for distributed transaction, including Saga, Tcc, XA, and OutBox, support orchestrating Mysql, Postgres, Mongo, Redis to composite a global transaction, and also provide utilities to make compensation, idempotency much more easier.

It is not true https://temporal.io/blog/workflow-engine-principles

**Comment by yedf2** [comment]
I had a look at the article whose link had been provided.

It is not easy to accomplish a distributed transaction using the workflow provided by temporal. How to do a Saga? How to do a Tcc?
