### ISSUE TITLE
[BUG] Extract Addr returning 127.0.0.1

### ISSUE THREAD

**Issue by titus-zx** [go-micro/go-micro#2448]
this function
https://github.com/asim/go-micro/blob/e5a35d38f931e61c07fdba47242753efc2bde494/util/addr/addr.go#L63

Somehow returning  `127.0.0.1` then causing error when we call the service while service running in kubernetes

**Comment by hellodudu** [comment]
Maybe check the order of the network ethers using `ifconfig`? @titus-zx 
![ifconfig](https://user-images.githubusercontent.com/519830/199156165-5e7e5b2d-4f06-49d5-8288-e22bd763cea3.png)

**Comment by lowryxiao** [comment]
@titus-zx Would you kindly elaborate how to reproduce this problem that you met? Since I couldn't reproduce it neither in my local docker container nor k8s pod.
