### ISSUE TITLE
About the problem that the plugin does not prompt the introduction of the package in goland

### ISSUE THREAD

**Issue by SupermanPro** [go-micro/go-micro#2457]
Hi, I think I need your help to solve this problem. This issue caused me to manually import the relevant packages when using the consul feature of the go-micro plugin in the goland IDE. After disabling manual import of packages, manual import is still required to use the feature again.
Below is my environment configuration
```shell
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\superman\AppData\Local\go-build
set GOENV=C:\Users\superman\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\superman\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\superman\go
set GOPRIVATE=
set GOPROXY=https://goproxy.io,direct
set GOROOT=F:\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=F:\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.17.8
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\GoWork\src\day22\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=C:\Users\superman\AppData\Local\Temp\go-build2476768690=/tmp
/go-build -gno-record-gcc-switches
```

![GIF](https://user-images.githubusercontent.com/47558436/159633372-9c4dddba-2769-4676-8706-96c5a3beeacf.gif)

Looking forward to your reply

**Comment by iqbalaydrus** [comment]
I don't think you can fix it. Every plugin has its own go.mod files and isn't installed by default. Because you don't want to include all the plugin dependencies in your project that you don't use.

But if you use it once in your project, the auto import will work as intended.
