### ISSUE TITLE
file=user/user.go:31 level=fatal mkdir C:\Users\wyzlhf\.micro: The system cannot find the path specified.

### ISSUE THREAD

**Issue by wyzlhf** [go-micro/go-micro#2461]
I have install go-micro with "go install github.com/micro/micro/v3@latest".then when I use "micro" CMD,file=user/user.go:31 level=fatal mkdir C:\Users\wyzlhf\.micro: The system cannot find the path specified.

**Comment by xpunch** [comment]
github.com/micro/micro is another project, maybe you should ask in [github.com/micro/micro/issues](https://github.com/micro/micro/issues)

**Comment by wyzlhf** [comment]
Thank you. Your email is received and will be handled  as soon as possible.谢谢。您的邮件已收到，我会尽快处理。
