### ISSUE TITLE
go-micro become too unstable to be used in production

### ISSUE THREAD

**Issue by morya** [go-micro/go-micro#2463]
My question,

go-micro is a great project, it has saved me and our tiny team quite a lot time.

But we come across some serial problems recently,

1. go-micro version changed too frequent
2. go-micro website changed too frequent
3. go-micro plugin and docs are not so up to date

go-micro v4 can't not be install with simple refer to docs.

just like this one: https://github.com/asim/go-micro/issues/2344 has bugged a lot people.

I just updated my project from v2 to v4, and I have been blocked by this problem too.
I have to dig into code, docs, and a lot things to figure it out.

I am not here to complain or point out that I shouldn't do that.

I just want to say, if, the project has these things 
- not so clearify docs
- not so stable versions
- hard to install and use (not very simple if I could say)

I think the project will loose quite a lot users, and potential mantainers.
Which could affect vitality for such a great opensource project.

Again, go-micro is still a great project.
Wonderful job

**Comment by asim** [comment]
I moved on from go-micro a long time ago. I appreciate you want support, docs, further maintenance but literally no one is being paid to do that. So my advice would be, find a library that's well supported. Go Micro was started 7 years ago. New libraries are coming out with fresh devs and new ideas that are better in the long term.

**Comment by morya** [comment]
Yes, I know the history about go-micro, go-nitro and m3o versions.

I understand this now.

**Comment by grissom1** [comment]
Or we can all start to contribute more via either issues or PR and help the maintain the project, since we all love it. I think that’s exactly the point for an open source project. Great job! @everyone

**Comment by morya** [comment]
I get the idea, 
so, what are the priorities right now?

1. do we have a leader or leaders for this prj, who can decide which should be attended to first
2. does this prj has some sort of donation still, so there could be more attenders be drawed to
3. what's the roadmap for this prj

**Comment by asim** [comment]
This is a personal project I built many years ago. Right now I'm still the owner of it. The years of work are mine along with those who contributed something along the way. There's no roadmap and no form of donations. I have done both of these in the past and wasted significant amount of effort to earn very little for my work. This project will not go that route again. 

My honest advice. Use something else. Go Zero, Kratos, GRPC, Go Kit. The number of projects is endless. Please don't push your agenda here to try to make this more than what it is. The owner of the project is quite literally telling you to use something else. That should be indication enough that this is just a project that sits on GitHub and nothing more.

**Comment by morya** [comment]
Thanks for your valuable time and patient answer.
Maybe it worth nothing, but this project is quite a beatiful and elegant work, I respect that.

Best wishes

**Comment by asim** [comment]
Thank you for your kind words. I know that you mean well and many others do too. Open source is just difficult for solo maintainers. While others could contribute more, no one ends up doing it full time.

At this point it's easier to just let go and have minor fixes.
