### ISSUE TITLE
Is go-micro deprecated?

### ISSUE THREAD

**Issue by pscheid92** [go-micro/go-micro#2464]
I stumbled across this paragraph that states `asim/go-micro` is deprecated:

> As part of v3 we’ve simplified the development model and consolidated the micro and [go-micro](https://github.com/asim/go-micro) libraries. This means that you, as the developer, only need to worry about leveraging the libraries offered in micro. Users of the now deprecated go-micro framework can follow this guide to upgrade their projects to use Micro v3.

Source: https://micro.dev/v2-to-v3-upgrade-guide

**Question**
Is it deprecated? Should we add a paragraph to the README file here?
I cannot find such a statement in the README file here. Thus I'm a bit confused.

**Comment by asim** [comment]
Go Micro moved to being a standalone framework. It's not part of Micro anymore. It's also not "deprecated". Make your own judgements based on its activity and functionality.

**Comment by pscheid92** [comment]
Yeah, that's why I was confused. Thank you very much for your clarification 😇
