### ISSUE TITLE
github.com/micro/protoc-gen-micro missing

### ISSUE THREAD

**Issue by ivybridge-3c33** [go-micro/go-micro#2472]
i've try go build service on jenkins but i got a problem that go.sum required github.com/micro/protoc-gen-micro 
but repository missing how to fix this?

ps. i'm using go-micro version 2

**Comment by 4k1k0** [comment]
Running the `go mod tidy` command on AWS CodePipeline:

```shell
go: downloading github.com/BurntSushi/toml v0.3.1
go: downloading github.com/ghodss/yaml v1.0.0
go: github.com/micro/go-micro@v1.18.0 requires
    github.com/micro/protoc-gen-micro@v1.0.0: reading github.com/micro/protoc-gen-micro/go.mod at revision v1.0.0: git ls-remote -q origin in /go/pkg/mod/cache/vcs/28cfbca4f5e41691076780b2017d5a1000b007b1d3d37b7a9d3b562c7adc9377: exit status 128:
    fatal: could not read Username for 'https://github.com': terminal prompts disabled
Confirm the import path was entered correctly.
If this is a private repository, see https://golang.org/doc/faq#git_https for additional information.

[Container] 2022/04/06 19:31:49 Command did not exit successfully go mod tidy exit status 1
```

**Comment by asim** [comment]
There are many repos that were migrated to a separate org when they were deprecated. That org has now been deleted. You should move to using https://github.com/asim/go-micro/tree/master/cmd/protoc-gen-micro instead.

**Comment by 4k1k0** [comment]
@asim is there a way to keep using the v1.18.0?

If I replace `github.com/micro/go-micro` with `github.com/asim/go-micro` in the go.mod file and the imports I get the following error message:

```
go: github.com/asim/go-micro@v1.18.0: parsing go.mod:
	module declares its path as: github.com/micro/go-micro
	        but was required as: github.com/asim/go-micro
```

**Comment by xpunch** [comment]
You can try [this](https://github.com/xpunch/go-micro-example/tree/main/v2):
```shell
go install github.com/micro/protoc-gen-micro@v2.1.0
```
or
```shell
go install github.com/micro/micro/cmd/protoc-gen-micro@v0.0.0-20200728170142-c7f7e4a71077
```

**Comment by xpunch** [comment]
Install Go Micro protoc-gen-micro:
V2
```
go install github.com/micro/protoc-gen-micro@v2.1.0
```
V3
```
go install github.com/asim/go-micro/cmd/protoc-gen-micro/v3@latest
```
V4
```
go install go-micro.dev/v4/cmd/protoc-gen-micro@v4
```

**Comment by 4k1k0** [comment]
@xpunch thank you.

----

I was able to update from `v1.18.0` to `v3.7.1` without so much hustle replacing `github.com/asim/go-micro v1.18.0` with `go-micro.dev/v4 v4.6.0` on my `go.mod` file.
