### ISSUE TITLE
Is  protoc-gen-micro repository deleted?

### ISSUE THREAD

**Issue by umishra21** [go-micro/go-micro#2478]
I have dependency on **protoc-gen-micro** in our project. But recently I have been gettting following error when trying to download the dependencies.

> go: github.com/micro/go-micro@v1.18.0 requires
> 	github.com/micro/protoc-gen-micro@v1.0.0: reading github.com/micro/protoc-gen-micro/go.mod at revision v1.0.0: unknown revision v1.0.0

Please help me with this issue.

Thanks

**Comment by asim** [comment]
Yes it's gone

**Comment by hpareek1996** [comment]
@umishra21 @asim Is there any fix which can be done for this ?

**Comment by asim** [comment]
Use the one in the cmd directory

**Comment by dungnt-htv** [comment]
@asim Sorry, that means we must to change github.com/micro/go-micro@1.18 to new version of go-micro.dev/v4 ?

**Comment by xpunch** [comment]
@dungnt-htv You can still use lower version of go-micro, but it's better to upgrade go-micro.dev/v4.
```
go install github.com/micro/protoc-gen-micro@v2.1.0
```
