### ISSUE TITLE
Does asim/go-micro has support for newrelic go-agent?

### ISSUE THREAD

**Issue by umishra21** [go-micro/go-micro#2483]
I was using micro/go-micro previously which had no issue running newrelic go-agent as it used micro/go-micro. But on updating my go-micro to v3 (asim/go-micro), i am facing issue since newrelic go-agent makes use of micro/go-micro. Does asim/go-micro has support for newrelic go-agent? 

```
# github.com/newrelic/go-agent/_integrations/nrmicro
../../../pkg/mod/github.com/newrelic/go-agent@v3.10.0+incompatible/_integrations/nrmicro/nrmicro.go:127:10: cannot use func literal (type func(context.Context, *"github.com/micro/go-micro/registry".Node, client.Request, interface {}, client.CallOptions) error) as type client.CallFunc in return argument
../../../pkg/mod/github.com/newrelic/go-agent@v3.10.0+incompatible/_integrations/nrmicro/nrmicro.go:130:13: cannot use node (type *"github.com/micro/go-micro/registry".Node) as type *"github.com/asim/go-micro/v3/registry".Node in argument to cf
make: *** [local] Error 2

```

Would be great if anyone can help on this.

Thanks

**Comment by polanskya** [comment]
So currently there is no support past original go micro.. We desperately need micro 3 and micro 4 newrelic integration, since imports with newrelic are different. . I have tried copied newrelic code locally and used it to some success, but we are missing stream wrapper integration since its using internal newrelic package.. 

The entire integration is not that hard.. On NR side they just need to have multi version support with different imports to match v3 and v4 on micro side.. 

https://github.com/newrelic/go-agent/blob/master/v3/integrations/nrmicro/nrmicro.go

Thanks

**Comment by polanskya** [comment]
@xpunch .. I took a stab at nrmicro-v3 integration.  Tests are broken but they seems to be broken in nrmicro as well. 

https://github.com/polanskya/go-agent/tree/nrmicro-v3/v3/integrations/nrmicro-v3

Thanks

**Comment by xpunch** [comment]
https://github.com/polanskya/go-agent/blob/b19f117d5a9d02a6da547c6a8b3f5514f501dac5/v3/integrations/nrmicro-v3/go.mod#L9
```
require (
	github.com/asim/go-micro/plugins/broker/memory/v3 v3.7.0
	github.com/asim/go-micro/plugins/registry/memory/v3 v3.7.0
	github.com/asim/go-micro/plugins/selector/registry v0.0.0-20210630082400-93ba8cd0dfc7
	github.com/asim/go-micro/v3 v3.7.0
	github.com/golang/protobuf v1.5.2
	github.com/newrelic/go-agent/v3 v3.15.1
)
```
If integrate with go micro v3, all plugins should be v3, the registry is not v3.

**Comment by polanskya** [comment]
@xpunch 

https://github.com/asim/go-micro/blob/v3/plugins/selector/registry/go.mod#L1

is not tagged with v3, hence i had to pull it my commit

**Comment by xpunch** [comment]
All go micro plugins were migrated into github.com/go-micro/plugins, maybe you can try https://github.com/go-micro/plugins/tree/main/v3.
```shell
go get github.com/go-micro/plugins/v3/selector/registry@latest
```

**Comment by polanskya** [comment]
Done
