### ISSUE TITLE
Does go-micro support yaml reader? #614 

### ISSUE THREAD

**Issue by uther518** [go-micro/go-micro#2487]
like https://github.com/asim/go-micro/issues/614

but  https://micro.mu/docs/go-config.html#set-source-encoder  page not exist

**Comment by xpunch** [comment]
https://github.com/go-micro/plugins/tree/main/v4/config/encoder/yaml

**Comment by xpunch** [comment]
https://github.com/go-micro/dashboard/blob/ebdb5127a231218db9e239c20419fae41781b245/config/load.go#L57-L60
Hope this can help you.
