### ISSUE TITLE
Should the default value of the parameter "register_interval" in CMD be -1?

### ISSUE THREAD

**Issue by bosima** [go-micro/go-micro#2488]
When I set 'RegisterInterval' in the server, it was overwritten by  'service.Init()'.
It's hard for developers to know what happened, so this is unreasonable!

    rpcServer := server.NewServer(
		    server.RegisterInterval(10*time.Second),
		    server.RegisterTTL(20*time.Second),
	    )
    ...
    service.Init()

I see an initial value set in 'CMD':
https://github.com/asim/go-micro/blob/367771923c07c51df3d50eac447a3e543a094b60/cmd/cmd.go#L76-L87

If set their initial value to -1, the developer's settings will not be overwritten.
https://github.com/asim/go-micro/blob/367771923c07c51df3d50eac447a3e543a094b60/cmd/cmd.go#L561-L567

I also saw the previous issue: #911 

or developers should remove 'service.Init()'?

**Comment by xpunch** [comment]
It's a known issue, this caused by the priority of config loading order.
As a workaround, you can pass register interval through service.Init().
```go
service.Init(micro.RegisterInterval(10 * time.Second))
```

**Comment by bosima** [comment]
> It's a known issue, this caused by the priority of config loading order. As a workaround, you can pass register interval through service.Init().
> 
> ```go
> service.Init(micro.RegisterInterval(10 * time.Second))
> ```
@xpunch 
It doesn't work. I've tested it with the master code.

it's just init Server:

https://github.com/asim/go-micro/blob/master/options.go#L254

    func RegisterInterval(t time.Duration) Option {
	    return func(o *Options) {
		    o.Server.Init(server.RegisterInterval(t))
	    }
    }

**Comment by xpunch** [comment]
As #911 discussed, you can try
```
service.Init()
service.Init(micro.RegisterInterval(10 * time.Second))
```

Why do you need to create rpcServer manually, why not access through service.Server()?

**Comment by bosima** [comment]
> RegisterInterval

Just want to change the options.

RegisterInterval and RegisterTTL

**Comment by bosima** [comment]
> As #911 discussed, you can try
> 
> ```
> service.Init()
> service.Init(micro.RegisterInterval(10 * time.Second))
> ```
> 
> Why do you need to create rpcServer manually, why not access through service.Server()?

Just want to change the options.

RegisterInterval and RegisterTTL
