### ISSUE TITLE
is github.com/asim/go-bson  removed?

### ISSUE THREAD

**Issue by leopay** [go-micro/go-micro#2490]
HI @asim ,  I find the latest code also required this repo

https://github.com/asim/go-micro/tree/master/plugins/codec/bsonrpc

but,  github.com/asim/go-bson was gone

**Comment by jakeisnt** [comment]
Yes - previous versions of go-micro are dependent on `asim/go-bson`, but it's been deleted. I recommend finding a cached version of the repository somewhere and forking it to your own github account to maintain compatibility.

**Comment by leopay** [comment]
> Yes - previous versions of go-micro are dependent on `asim/go-bson`, but it's been deleted. I recommend finding a cached version of the repository somewhere and forking it to your own github account to maintain compatibility.

Do you know somewhere has a cached version of this repo, could you share it?

**Comment by xpunch** [comment]
Try github.com/go-micro/go-bson

**Comment by leopay** [comment]
thx, @xpunch
