### ISSUE TITLE
go get Responds with repository not found

### ISSUE THREAD

**Issue by mehdimirabian** [go-micro/go-micro#2494]
No matter how I try to install your packages I continue to get repo not found.

❯ go get -u github.com/micro/protoc-gen-micro@v1.0.0
go: github.com/micro/go-micro@v1.18.0 requires
	github.com/micro/protoc-gen-micro@v1.0.0: reading github.com/micro/protoc-gen-micro/go.mod at revision v1.0.0: git ls-remote -q origin in /Users/mmirabi/go/pkg/mod/cache/vcs/28cfbca4f5e41691076780b2017d5a1000b007b1d3d37b7a9d3b562c7adc9377: exit status 128:
	remote: Repository not found.
	fatal: repository 'https://github.com/micro/protoc-gen-micro/' not found
❯ go install github.com/micro/protoc-gen-micro@v1.0.0
go: github.com/micro/protoc-gen-micro@v1.0.0: github.com/micro/protoc-gen-micro@v1.0.0: invalid version: git ls-remote -q origin in /Users/mmirabi/go/pkg/mod/cache/vcs/28cfbca4f5e41691076780b2017d5a1000b007b1d3d37b7a9d3b562c7adc9377: exit status 128:
	remote: Repository not found.
	fatal: repository 'https://github.com/micro/protoc-gen-micro/' not found

**Comment by jmillerv** [comment]
Unfortunately, I think this repo was deleted. I'm in the same boat trying to get a workaround going.

**Comment by Davincible** [comment]
`go install go-micro.dev/v4/cmd/protoc-gen-micro@v4`
