### ISSUE TITLE
malformed header: missing HTTP content-type

### ISSUE THREAD

**Issue by tvluongict** [go-micro/go-micro#2497]
Hi @asim 
My application includes: 1 GRPC-Gateway & 1 GRPC server
My client send a restful request to grpc-gateway and then gateway redirect request to grpc server, everything is ok but there is only an error when gateway return response.
Sometime it return error: malformed header: missing HTTP content-type, sometimes its ok.

 `{
    "error": "malformed header: missing HTTP content-type",
    "code": 2,
    "message": "malformed header: missing HTTP content-type"
}`

or 
`{
    "StatusCode": "success",
    "StatusDescription": "Success"
}`

How can I resolve it?

**Comment by medivh666** [comment]
I met the same problem, have you solved it

**Comment by medivh666** [comment]
@tvluongict   I resolve it
"github.com/asim/go-micro/plugins/server/grpc/v4"

opts := []micro.Option{
		micro.Server(grpc.NewServer()),
		micro.Address(conf.Service.ListenHost()),
		micro.Name(conf.Service.ServiceName),
		micro.Version(conf.Service.Version),
		micro.Registry(consulRegistry),
		micro.WrapHandler(RecoverWrapper),
	}

**Comment by Davincible** [comment]
To elaborate, the default server used in go-micro is a json/http server. Trying to access it as a gRPC server will give a rather vague content-type error indeed, as they are not compatible. 

Like @medivh666 showed, to use it as gRPC server you need to explicitly pass the gRPC server type in the setup options.

You can create a gRPC server by default by passing in the `--grpc` flag in the go-micro CLI

```bash
go-micro new service --grpc helloworld
```

**Comment by tvluongict** [comment]
Thanks @medivh666  @Davincible
