### ISSUE TITLE
[BUG] Account not found with this ID

### ISSUE THREAD

**Issue by mefloresz** [go-micro/go-micro#2502]
**Describe the bug**

hi Guys i have a problem when i try to conect with micro using the admin credentials 

micro login
Enter username: admin
Enter password:
Account not found with this ID

i try to create another account with Admin profile but the Micro server needs an account for this ...

micro login
Enter username: admin
Enter password:
Account not found with this ID

micro auth create account --scopes=admin mario
Error creating account: {"id":"auth.Auth.Generate","code":401,"detail":"an account is required","status":"Unauthorized"}

Go version : v1.17.10
Micro version v3.5.0

SO: WSL ( windows subsystem Linux) V 20.04

**Comment by asim** [comment]
Wrong repo. Please file in github.com/micro/micro
