### ISSUE TITLE
Go micro installation on Kubernetes with helm chart

### ISSUE THREAD

**Issue by roynilanjan** [go-micro/go-micro#2503]
Before asking, please check if your question has already been answered: 

1. Check the documentation - https://micro.mu/docs/
2. Check the examples and plugins - https://github.com/micro/examples & https://github.com/micro/go-plugins
3. Search existing issues
I installed micro with helm chart following this link https://artifacthub.io/packages/helm/micro/micro  . After installing I have run the following commands :
kubectl port-forward svc/proxy -n micro 8081:443 . It is successfully forwarding ports :
Forwarding from 127.0.0.1:8080 -> 443
Forwarding from [::1]:8080 -> 443
Handling connection for 8080
However when I run the command :
micro services .
I get "Not authorized to perform this request" message
Same error I get while I access my service deployed on kubernetes cluster.
I am following this blog post https://itnext.io/go-micro-on-kubernetes-getting-started-2959dd6c2d4f to deploy a service . I am geting  "Not authorized to perform this request" message while accessing the service. can you help resolve the issue please.

**Comment by asim** [comment]
This is unrelated to go-micro. I think you're looking for github.com/micro/micro. You may need to login using `micro login` before issuing further commands. Please refile the issue in the right repo. Also see. https://micro.dev/reference
