### ISSUE TITLE
the different between plugins repo

### ISSUE THREAD

**Issue by shikbupt** [go-micro/go-micro#2506]
I find two repo of go-micro plugins. one is the subdirectory of asim/go-micro, the other is github.com/go-micro/plugins.
what is the different of the two plugins? which one should I use?

**Comment by asim** [comment]
Plugins in asim/go-micro are legacy v3 and older. The go-micro org is the home of all new and community maintained plugins.

**Comment by shikbupt** [comment]
thanks
