### ISSUE TITLE
How to run api gateway at v4?

### ISSUE THREAD

**Issue by ivybridge-3c33** [go-micro/go-micro#2507]
I'm trying to upgrade go-micro from v2 to v4 and stuck at api gateway
at go-micro version 2, the code of api gateway 
#### main.go
```
package main

import (
	"os"

	"github.com/micro/go-micro/v2"
	"github.com/micro/go-plugins/registry/kubernetes/v2"
	"github.com/micro/micro/v2/cmd"
)

func main() {
	configs := make([]micro.Option, 0)
	if os.Getenv("MICRO_REGISTRY") == "kubernetes" {
		configs = append(configs, micro.Registry(kubernetes.NewRegistry()))
	}
	cmd.Init(configs...)
}

```

#### plugin.go
```
package main

import (
	"github.com/micro/go-plugins/micro/cors/v2"
	_ "github.com/micro/go-plugins/registry/consul/v2"
	"github.com/micro/micro/v2/client/api"
)

func init() {
	api.Register(cors.NewPlugin())
}

```

and run like this
```
MICRO_SERVER_NAME='local.test.grpc.gateway' MICRO_CLIENT=grpc MICRO_SERVER=grpc go run main.go plugin.go \
	--registry=consul api \
	--namespace='local.test.grpc' \
	--cors-allowed-origins=* \
	--cors-allowed-methods=POST,GET,PUT,DELETE \
	--enable_rpc=true --address=0.0.0.0:8080

```

but now i don't know how to run api gateway at version 4 and if i try to call api to service version 4 at api-gateway version 2 it's show error 

```
{"id":"go.micro.client","code":500,"detail":"stream terminated by RST_STREAM with error code: PROTOCOL_ERROR","status":"Internal Server Error"}
```

please someone help me

**Comment by Davincible** [comment]
v4 doesn't have an api gateway, see https://github.com/asim/go-micro/issues/2343#issuecomment-978869019

**Comment by ivybridge-3c33** [comment]
thank you

**Comment by asim** [comment]
It's more likely that we iterate on the api package to enable you to create your own api gateway like a micro api.

**Comment by Davincible** [comment]
@asim what was the thought behind that? Is there any benefit to it?

**Comment by asim** [comment]
A lot of people want to run a http API in the same process so that's one potential use case. The other is a composable and pluggable API gateway. Hard thing with the micro API was needed to modify and rebuild for that.

**Comment by Davincible** [comment]
@ivybridge-3c33 this PR might be interesting to you;
 https://github.com/asim/go-micro/pull/2522

**Comment by ivybridge-3c33** [comment]
i'll try it think you very much mr. @Davincible @asim
