### ISSUE TITLE
exec the command( protoc --proto_path=$GOPATH/src:. --micro_out=. --go_out=. greeter.proto ), out the error 

### ISSUE THREAD

**Issue by GZ-Alinx** [go-micro/go-micro#2516]
/src:.: warning: directory does not exist.
greeter.proto: File does not reside within any path specified using --proto_path (or -I).  You must specify a --proto_path which encompasses this file.  Note that the proto_path must be an 
exact prefix of the .proto file names -- protoc is too dumb to figure out when two paths (e.g. absolute and relative) are equivalent (it's harder than you think).

**Comment by Davincible** [comment]
What's your full proto command and what does your dir structure look like?

**Comment by GZ-Alinx** [comment]
code for the site: https://github.com/asim/go-micro/tree/master/cmd/protoc-gen-micro,
full command:  protoc --proto_path=$GOPATH/src:. --micro_out=. --go_out=. greeter.proto

**Comment by GZ-Alinx** [comment]
![image](https://user-images.githubusercontent.com/30387309/176072662-51f981f0-a841-4e3d-9c47-2ee918eed86a.png)

![image](https://user-images.githubusercontent.com/30387309/176072763-7a4958aa-7f43-4f65-ac9d-2fafdbb04ea0.png)

**Comment by Davincible** [comment]
Ah, I see. I recommend using the [cli](https://github.com/go-micro/cli) to create a template with 

```bash 
go-micro new github.com/GZ-Alinx/hello-world
```

That will make everything clear. You can find the proto command in the `Makefile`

**Comment by xpunch** [comment]
If the source codes is not in $GOPATH/src, then you should use:
```
protoc --proto_path=. --micro_out=. --go_out=. greeter.proto
```

**Comment by xpunch** [comment]
The document is out of date.

**Comment by GZ-Alinx** [comment]
> ```shell
> go-micro
> ```

the go-micro command where download?    I see the site learning "https://github.com/asim/go-micro"

**Comment by GZ-Alinx** [comment]
this is test code,  I think 

> If the source codes is not in $GOPATH/src, then you should use:
> 
> ```
> protoc --proto_path=. --micro_out=. --go_out=. greeter.proto
> ```

![image](https://user-images.githubusercontent.com/30387309/176089313-cfcf5fe2-006f-479c-93c7-539b0333cb75.png)
 I use the command , result up image error ,  the command exec on windows11 system,  go-micro learning where site , new site?

**Comment by xpunch** [comment]
I think the error tips has described it clearly, go_package is missing.

**Comment by GZ-Alinx** [comment]
think you!  add config  "option go_package = "/micro";"  on success~
