### ISSUE TITLE
How can I get the locally registered registry node information of the current service

### ISSUE THREAD

**Issue by JellyTony** [go-micro/go-micro#2523]
How can I get the locally registered registry node information of the current service？

**Comment by xpunch** [comment]
https://github.com/asim/go-micro/blob/48d6650f285e5cbf4b1fc7c30a5c6ee3b1a0c15b/registry/registry.go#L26

**Comment by JellyTony** [comment]
> https://github.com/asim/go-micro/blob/48d6650f285e5cbf4b1fc7c30a5c6ee3b1a0c15b/registry/registry.go#L26

This is to get the remote, I want to get the locally registered, not including the other nodes

**Comment by xpunch** [comment]
Maybe you need to build your own registry.Service locally.
https://github.com/asim/go-micro/blob/48d6650f285e5cbf4b1fc7c30a5c6ee3b1a0c15b/server/rpc_server.go#L640

**Comment by JellyTony** [comment]
Yes, these key things are packaged and cannot be obtained externally. Unless the package is rewritten without using the default, it seems that it cannot be obtained

**Comment by Davincible** [comment]
I was looking for the same thing, and found out that you can list all services and filter by node ID to get your current service.

To know the node ID of your current service, you have to set it manually:

```go
// main.go

// Set random node ID
node := uuid.New().String()

// Init service
srv.Init()
srv.Server().Init(
    server.Id(node),
)
```

Then you can get all nodes with your current service name
```go
services := srv.Options().Registry.GetService(Service)
if err != nil {
    return errors.Wrap(err, "Failed to get service list")
}

if len(services) == 0 {
    return errors.New("Service list is empty")
}


for _, serviceNode := range services[0].Nodes {
    if serviceNode.Id == node {
        // Do something
    }
}
```

**Comment by JellyTony** [comment]
I thought about a similar solution, but I should expose this part inside the framework

**Comment by asim** [comment]
The first question is. Why do you need this information locally? The second question is surely it's just going to bloat the server to do so?

**Comment by JellyTony** [comment]
> The first question is. Why do you need this information locally? The second question is surely it's just going to bloat the server to do so?

For example, if I start a `Server`, but I don't specify the connection address, then mocro will automatically start a service on a random port internally, at this time I want to know externally on what port the service is started, it will not be available, as to why I didn't specify the port, because the service can start multiple instances, why do I want to get the connection address? Because, for example, Prometheus monitoring needs to leak an http route, Prometheus will catch through this route

**Comment by asim** [comment]
Just lookup server.Options().Address after its started

**Comment by JellyTony** [comment]
Obtained is: `:0`

![image](https://user-images.githubusercontent.com/106534114/180491877-4cd6d4f4-d46c-407b-bfb6-a30c91cb9b5f.png)
![image](https://user-images.githubusercontent.com/106534114/180491890-21364d8a-e0d4-45ae-95ec-7b8a5211ced3.png)

**Comment by Davincible** [comment]
@JellyTony note that you can also specify the port on which your service should listen to, so it can be the same for all services. 

```
MICRO_SERVER_ADDRESS=[::]:41888
```
