### ISSUE TITLE
can't create a web sevice template 

### ISSUE THREAD

**Issue by 567MEI13** [go-micro/go-micro#2524]
Before asking, please check if your question has already been answered: 
 how to create a web sevice by cmd
1. Check the documentation - https://micro.mu/docs/
2. Check the examples and plugins - https://github.com/micro/examples & https://github.com/micro/go-plugins
3. Search existing issues

**Comment by Davincible** [comment]
Use the [cli](https://github.com/go-micro/cli)

**Comment by xpunch** [comment]
Take a look at https://github.com/go-micro/dashboard, which is a web project based on go micro.
