### ISSUE TITLE
[BUG] When using grpc protocol, Abnormal communication between services

### ISSUE THREAD

**Issue by medivh-jay** [go-micro/go-micro#2533]
## Service initialization code snippet
```
import (
	grpcClient "github.com/asim/go-micro/plugins/client/grpc/v4"
	"github.com/asim/go-micro/plugins/server/grpc/v4"
)

srv := micro.NewService(
		micro.Server(grpc.NewServer()),
		micro.Client(grpcClient.NewClient()),
		micro.Name(service),
		micro.Version(version),
		micro.Action(func(context *cli.Context) error {
			if context.IsSet("config") {
				return config.LoadFile(context.String("config"))
			}
			return nil
		}),
		micro.Registry(etcd.NewRegistry()),
		micro.BeforeStart(func() error {
			return dao.Migrate()
		}),
	)

```

Many of my services are built on this, Exceptions will occur when they communicate with each other

```
{
  "error": {
    "id": "go.micro.client.transport",
    "code": 500,
    "detail": "malformed HTTP response \"\\x00\\x00\\x06\\x04\\x00\\x00\\x00\\x00\\x00\\x00\\x05\\x00\\x00@\\x00\"",
    "status": "Internal Server Error"
  },
  "success": false
}
```

**Comment by medivh-jay** [comment]
When I annotate these two lines of code, the communication is successful
```
micro.Server(grpc.NewServer()),
micro.Client(grpcClient.NewClient()),
```

But I need grpc

**Comment by asim** [comment]
Are you doing anything with flags? Sometimes that can affect it. Essentially you've got this error because a default client of some kind is attempting to call a grpc server.

**Comment by medivh-jay** [comment]
I used --config to get the path of my configuration file. This happens when I call service B in service A. according to debug, it is found that there is an error in the communication between service a and service B, how can I fix this problem?

Thank you very much for your help

**Comment by asim** [comment]
The error continues to imply that one service is not using the grpc client. So when you make that call, if you are not using `service.Client()` then it will fail. Assuming you do `client.DefaultClient` it will fail.

**Comment by medivh-jay** [comment]
I see. Thank you for your reply. I will try to specify `service.Client()`.
