### ISSUE TITLE
How to implement dual stack listening?

### ISSUE THREAD

**Issue by Super-zhw** [go-micro/go-micro#2535]
Currently, there is a scenario where my service node has two network cards, one is IPv4 and the other is IPv6, and the two network cards represent different networks.

![image](https://user-images.githubusercontent.com/34789750/181418252-dc8ac59d-216e-4fda-8e02-b50678bd6cc9.png)

In the case of not being able to listen to the "0.0.0.0" address. 
go-micro can only listen on one of the network cards.
How to make go-micro listen to two network cards?

**Comment by asim** [comment]
Depending on what server you're using you'd need to write one that can listen on two addresses.

**Comment by Super-zhw** [comment]
> Depending on what server you're using you'd need to write one that can listen on two addresses.

I've implemented a similar component, but instead of a server, it's a dual stack listener.It allows my server to listen on multiple addresses.
![image](https://user-images.githubusercontent.com/34789750/181520320-f61bd618-6873-41f0-b01b-3ffdfe9f8df9.png)
My server, when using go-micro, is just one last step away and I don't want to give up on that implementation.
I very much hope that you can implement the todo function in the link and turn on the listening injection function.
https://github.com/asim/go-micro/blob/master/transport/http_transport.go#L565

**Comment by asim** [comment]
I have no plans to personally implement anything but you're welcome  to contribute something

**Comment by Super-zhw** [comment]
Ok, thank you very much, I will give you a PR today, I hope it can be merged into master.
