### ISSUE TITLE
etcd get toml配置失败

### ISSUE THREAD

**Issue by yangyazhen** [go-micro/go-micro#2539]
github.com/asim/go-micro/v3/config/encoder 包下没有toml包，使用自定义的tomlEncoder结构，后报错，请问下用github.com/asim/go-micro/v3/包，怎么能获取etcd toml配置

**代码：**
func getTOML(pr string) error {
	//配置中心使用etcd key/value 模式
	etcdSource := metcd.NewSource(
		//设置配置中心地址
		metcd.WithAddress("127.0.0.1:2379"),
		//设置前缀，不设置默认为 /micro/config
		metcd.WithPrefix("/micro/config/"+pr),
		source.WithEncoder(NewEncoder()),
		//是否移除前缀，这里设置为true 表示可以不带前缀直接获取对应配置,StripPrefix 从语义上看是去掉前缀的意思，如果没有去掉前缀，则会保留micro、etcd这两个key
		metcd.StripPrefix(true),
	)
	//加载配置
	err := mconfig.Load(etcdSource)
	fmt.Println("5555555", err)
	return err
}

type tomlEncoder struct{}

func (t tomlEncoder) Encode(v interface{}) ([]byte, error) {
	b := bytes.NewBuffer(nil)
	defer b.Reset()
	err := toml.NewEncoder(b).Encode(v)
	fmt.Println("2222222222", err)
	if err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

func (t tomlEncoder) Decode(d []byte, v interface{}) error {
	err := toml.Unmarshal(d, v)
	fmt.Println("33333333333", err)
	return err
}

func (t tomlEncoder) String() string {
	return "toml"
}

func NewEncoder() encoder.Encoder {
	return tomlEncoder{}
}

**错误：**
5555555 invalid character 'i' in literal true (expecting 'r')

**配置：**
[main]
local_ip = ""

**Comment by Davincible** [comment]
@yangyazhen do you still have this issue? If so could you please format your code properly in backticks (`) like this

\```
..some code..
\```

**Comment by hellodudu** [comment]
try this plugin [https://github.com/go-micro/plugins/tree/main/v3/config/encoder/toml](https://github.com/go-micro/plugins/tree/main/v3/config/encoder/toml), new a config object and pass toml encoder to reader, finally pass config to MicroService as an option. Probably like this code:
```go
        // new config
	conf, err := config.NewConfig(
		config.WithSource(etcd.NewSource(
			source.WithEncoder(toml.NewEncoder()),
		)),
		config.WithReader(
			json.NewReader(
				reader.WithEncoder(toml.NewEncoder()),
			),
		),
	)

        // new micro service
        micro.NewService(
                 ...
		micro.Config(conf),
                 ...
	)
```
@yangyazhen 
Good Luck~
