### ISSUE TITLE
Can't find protoc-gen-micro plugin for go micro v4

### ISSUE THREAD

**Issue by agsimfzi** [go-micro/go-micro#2541]
When i run `go install go-micro.dev/v4/cmd/protoc-gen-micro@v4`
i got an error like this `go: go-micro.dev/v4/cmd/protoc-gen-micro@v4: module go-micro.dev/v4@v4 found (v4.8.0), but does not contain package go-micro.dev/v4/cmd/protoc-gen-micro`

**Comment by agsimfzi** [comment]
i has been found the solution

**Comment by wx-satellite** [comment]
> i has been found the solution

how to solve this problem？

**Comment by xpunch** [comment]
https://github.com/asim/go-micro/issues/2526
