### ISSUE TITLE
Can't find go-micro.dev/v4/api for go micro v4

### ISSUE THREAD

**Issue by agsimfzi** [go-micro/go-micro#2542]
When i run `go mod tidy`
i got an error like this `go-micro.dev/v4/api: go-micro.dev/v4/api@v1.18.0: parsing go.mod:
        module declares its path as: github.com/micro/go-micro
                but was required as: go-micro.dev/v4/api`

**Comment by lhqbalabala** [comment]
First execute the “go get go-micro.dev/v4” command
