### ISSUE TITLE
[BUG] go-micro registry node nil pointer

### ISSUE THREAD

**Issue by gdgrc** [go-micro/go-micro#2546]
**Describe the bug**

1. What are you trying to do?
- Build a Rpc Client to request a Rpc Server
3. What did you expect to happen?
- when rpc client try to get rpc server addr and request, "nil pointer exception" should not happen
5. What happens instead?
* a panic occur which have already get a Rlock wihout unlock
```
/usr/local/go17/src/runtime/panic.go:221 (0xc76946)
/usr/local/go17/src/runtime/signal_unix.go:735 (0xc76916)
mydir/pkg/mod/go-micro.dev/v4@v4.5.0/util/registry/util.go:65 (0x1226a8c)
mydir/pkg/mod/go-micro.dev/v4@v4.5.0/util/registry/util.go:85 (0x1226cfc)
mydir/pkg/mod/go-micro.dev/v4@v4.5.0/registry/cache/cache.go:126 (0x1228a78)
mydir/pkg/mod/go-micro.dev/v4@v4.5.0/registry/cache/cache.go:436 (0x122a95d)
mydir/pkg/mod/go-micro.dev/v4@v4.5.0/selector/default.go:52 (0x127feeb)
mydir/pkg/mod/github.com/asim/go-micro/plugins/client/grpc/v4@v4.0.0-20220118152736-9e0be6c85d75/grpc.go:90 (0x1de1242)
mydir/pkg/mod/github.com/asim/go-micro/plugins/client/grpc/v4@v4.0.0-20220118152736-9e0be6c85d75/grpc.go:403 (0x1de4df6)
myframework.git@v1.13/gomicro/wrap.go:595 (0x1e0c50c)
myframework.git@v1.13/gomicro/wrap.go:575 (0x1e0b99e)
myframework.git@v1.13/gomicro/wrap.go:312 (0x1e0936f)
myproject/cmu.pb.micro.go:238 (0x1b71d4e)
myproject/upcw_service.go:53 (0x1c0f57a)
myproject/upcw_common.go:33 (0x1e52904)
mydir/pkg/mod/github.com/gin-gonic/gin@v1.5.0/context.go:147 (0x1abd0ea)
myframework.git@v1.1.4-0.20220811072139-3a575069cde8/middleware/http/recovery.go:39 (0x1abd0d4)
mydir/pkg/mod/github.com/gin-gonic/gin@v1.5.0/context.go:147 (0x1af3dca)
myproject/comm/middleware/session/session.go:82 (0x1af3dad)
mydir/pkg/mod/github.com/gin-gonic/gin@v1.5.0/context.go:147 (0x1af714d)
myproject/comm/metadata/metadata.go:113 (0x1af7134)
mydir/pkg/mod/github.com/gin-gonic/gin@v1.5.0/context.go:147 (0x1ab8ef3)
myframework.git@v1.1.4-0.20220811072139-3a575069cde8/middleware/http/gin.go:293 (0x1ab8d73)
mydir/pkg/mod/github.com/gin-gonic/gin@v1.5.0/context.go:147 (0x116c369)
mydir/pkg/mod/github.com/gin-gonic/gin@v1.5.0/gin.go:403 (0x116bfb9)
mydir/pkg/mod/github.com/gin-gonic/gin@v1.5.0/gin.go:364 (0x116bb33)
mydir/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 (0x1cb0b6e)
/usr/local/go17/src/net/http/server.go:2879 (0xf0ee7a)
/usr/local/go17/src/net/http/server.go:1930 (0xf0a467)
/usr/local/go17/src/runtime/asm_amd64.s:1581 (0xc945a0)
```
* a goroutine panic with lock and other goroutine can't get the lock: pprof 
![image](https://user-images.githubusercontent.com/18026719/184593319-21f81507-6130-4988-8e63-ce0b53d83559.png)

* cause other goroutine can not get lock resource until I restart it.

**How to reproduce the bug:**
I do not know how to reproduce and why happen. I found it in product environment sometime and I have to restart the program to fix it or the program can not make rpc request. 

**Environment:**
Go Version: please paste `go version` output here
```

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/myname/.cache/go-build"
GOENV="/home/myname/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/myname/goproject17/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/myname/goproject17"
GOPRIVATE=""
GOPROXY=""
GOROOT="/usr/local/go17"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go17/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.6"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build4281984978=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by gdgrc** [comment]
Can anyone help? We get this bug in our  prod environment, It may show at any time, We can only restart the program to fix it by hand. I need your help hardly.

**Comment by Davincible** [comment]
Can you provide the complete error you get, not only the stack trace?

**Comment by gdgrc** [comment]
The code run in the backend server without ui, this is all I can get and I think it's enough for you to find out bug if it is a bug of gomicro.  At the same time,We are trying to get it through but nothing have got. By the way, what information do you want?

**Comment by Davincible** [comment]
You don't need a UI, just the logs. I am looking for the full log error messages, not only the stack trace.

It is for sure a bug in go-micro. I have looked at the stack trace and the code. But I can't figure out what is causing the error.

According to you your stacktrace, the nil pointer exception is here on line 65;
https://github.com/asim/go-micro/blob/a702a1b097bf56f1c35cc45db9b876610d2b3ea7/util/registry/util.go#L61-L68

The nil pointer exception doesn't make sense to me in this context, as the node is directly obtained from the for-loop.

Which gets called from here on line 128, where the locks are located;
https://github.com/asim/go-micro/blob/a702a1b097bf56f1c35cc45db9b876610d2b3ea7/registry/cache/cache.go#L117-L134

However, from the information you have provided and the code, I can't figure out what exactly is going wrong. So without more information or reproducing the bug it is difficult to help :)

**Comment by Davincible** [comment]
Also, I see you are using go-micro v4.5.0, you can try upgrading to the latest version and see if that helps anything

**Comment by gdgrc** [comment]
Yeah, We just upgrade gomicro from v.1.8.0 to v4.5.0. What you have located is right, I also do the same thing. As for the code `*n = *node ` , n is newed just now,  the only possibility is that the node is nil. I have tried to traced the code but can not find anything. But Obviously, a simple patch is to check if node is nil and when it is nil, pass it.
Sorry, I do not quite understand  “the full log error messages, not only the stack trace.”. How can I get this information? 

Our architecture: We have two front server: webapi , oauth2 who receive http request from frontend like web,app.  And We have  three back server: commutils, account, auth. Only front server can call back server with gomicro by grpc. The registry info is stored in etcd. The panic occurs when front server call back server.

About "Also, I see you are using go-micro v4.5.0, you can try upgrading to the latest version and see if that helps anything", It's a good idea. But changing the framework may cause full test of our project which costs much. We have finished full test when I upgrade it from v1.8.0 to v4.5.0. If I upgrade it again, I should have proper and accurate reason to convince my teamates which mean we should have accurate code trace to prove the old framework cause the bug and the new will not.

**Comment by gdgrc** [comment]
hello? can anyone help?

**Comment by Davincible** [comment]
@gdgrc how is it going now with the service?

I want to help you and have looked at it again, but I can't figure out why the exception is happening. Have you been able to reproduce it?

**Comment by gdgrc** [comment]
@Davincible Crash occasionaly. 
I add some log in gomicro.
![image](https://user-images.githubusercontent.com/18026719/192172375-48bc42ac-8822-4472-9e26-febd7cd1b1f0.png)
```
[zz] 2022/09/24 21:35:55 gomicro inner panic sence: service.Nodes:[0xc0044987b0 0xc0044987e0 0xc004498810 0xc004498840 0xc004498960 0xc004498ae0 <nil> <nil> <nil> <nil> <nil> <nil>] service: &{Name:credential Version:latest Metadata:map[] Endpoints:[0xc004498c00 0xc004498c30 0xc004498c60 0xc004498cc0 0xc004498cf0 0xc004498d20 0xc004498d50] Nodes:[0xc0044987b0 0xc0044987e0 0xc004498810 0xc004498840 0xc004498960 0xc004498ae0 <nil> <nil> <nil> <nil> <nil> <nil>]}
[zz] 2022/09/24 21:35:55 gomicro inner panic sence: service.Nodes:[0xc0044987b0 0xc0044987e0 0xc004498810 0xc004498840 0xc004498960 0xc004498ae0 <nil> <nil> <nil> <nil> <nil> <nil>] service: &{Name:credential Version:latest Metadata:map[] Endpoints:[0xc004498c00 0xc004498c30 0xc004498c60 0xc004498cc0 0xc004498cf0 0xc004498d20 0xc004498d50] Nodes:[0xc0044987b0 0xc0044987e0 0xc004498810 0xc004498840 0xc004498960 0xc004498ae0 <nil> <nil> <nil> <nil> <nil> <nil>]}
[zz] 2022/09/24 21:35:56 gomicro inner panic sence: service.Nodes:[0xc0044987b0 0xc0044987e0 0xc004498810 0xc004498840 0xc004498960 0xc004498ae0 <nil> <nil> <nil> <nil> <nil> <nil>] service: &{Name:credential Version:latest Metadata:map[] Endpoints:[0xc004498c00 0xc004498c30 0xc004498c60 0xc004498cc0 0xc004498cf0 0xc004498d20 0xc004498d50] Nodes:[0xc0044987b0 0xc0044987e0 0xc004498810 0xc004498840 0xc004498960 0xc004498ae0 <nil> <nil> <nil> <nil> <nil> <nil>]}
[zz] 2022/09/24 21:35:57 gomicro inner panic sence: service.Nodes:[0xc0044987b0 0xc0044987e0 0xc004498810 0xc004498840 0xc004498960 0xc004498ae0 <nil> <nil> <nil> <nil> <nil> <nil>] service: &{Name:credential Version:latest Metadata:map[] Endpoints:[0xc004498c00 0xc004498c30 0xc004498c60 0xc004498cc0 0xc004498cf0 0xc004498d20 0xc004498d50] Nodes:[0xc0044987b0 0xc0044987e0 0xc004498810 0xc004498840 0xc004498960 0xc004498ae0 <nil> <nil> <nil> <nil> <nil> <nil>]}
[zz] 2022/09/24 21:56:02  --- restarting----
[zz] 2022/09/24 21:56:02 ----------version info----------
```

I a lso add log:
* cache create or update
![image](https://user-images.githubusercontent.com/18026719/192172576-7a680fd8-904d-4f1e-9cf2-f4d29b5a6397.png)
* cache delete
![image](https://user-images.githubusercontent.com/18026719/192172602-5dfe1351-248b-491b-9285-0fd62009c890.png)

But I only get the log in panic. I started the service at 2022-09-13 15:04:56 and it crashed at 2022-09-24 21:35:55. The Log is rotated  by 7 days which means we can only see the last 7 days log.

When panic comes, there are 12 nodes printed and 6 of the are nil which match the num of our division: We have 12 rpc server in the product env , 6 have envCode and 6 haven't. Filter by the function below:

```go
func main(){

         // new micro client
	cliOpts := []client.Option{
		client.Wrap(zgomicro.GenerateClientEnvCodeFilterWrap(s.options.EnvCode, s.options.EnvStrict)),
		client.Wrap(zgomicro.GenerateClientPromWrap(s.ng)),
	}
        .... new micro client

        // new micro server 
        grpcS := grpc.NewServer(
		server.Advertise(conf.Advertise),
	)

	// init metadata
	md := make(map[string]string)
	if conf.EnvCode != "" {
		md[_envCode] = conf.EnvCode
	}

	o := []micro.Option{
		micro.Server(grpcS),
		micro.Registry(reg),
		micro.Name(conf.ServiceName),
		micro.Address(fmt.Sprintf(":%d", conf.ServerPort)),
		micro.RegisterTTL(15 * time.Second),
		micro.RegisterInterval(10 * time.Second),
		micro.Metadata(md),

	}
	o = append(o, opts...)
	s := micro.NewService(o...)
        ......
}


func GenerateClientEnvCodeFilterWrap(envCode string, strict bool) func(c client.Client) client.Client {
	return func(c client.Client) client.Client {
		return &clientEnvCodeFilterWrap{
			Client:    c,
			envCode:   envCode,
			envStrict: strict,
		}
	}
}

type clientEnvCodeFilterWrap struct {
	client.Client
	envCode   string
	envStrict bool
}

func (c *clientEnvCodeFilterWrap) Call(ctx context.Context, req client.Request, rsp interface{}, opts ...client.CallOption) (err error) {
	envCode := c.envCode
	envStrict := c.envStrict
	// Add function to filter target services according to metadata tag
	envFilter := func(svcs []*registry.Service) []*registry.Service {
		got := make([]*registry.Service, 0)
		noTagSvc := make([]*registry.Service, 0, len(svcs))
		for _, svc := range svcs {
			if req.Service() != svc.Name {
				got = append(got, svc) //TODO: not necessary
				continue
			}
			nodes := make([]*registry.Node, 0, len(svc.Nodes))      //Nodes with tags
			noTagNodes := make([]*registry.Node, 0, len(svc.Nodes)) // Nodes without tags
			for _, node := range svc.Nodes {
				env, ok := node.Metadata[_envCode]
				if len(env) == 0 {
					noTagNodes = append(noTagNodes, node)
				}
				// when client service has envCode, choose server services who have the same envCode
				if envCode != "" {
					if ok && env == envCode {
						nodes = append(nodes, node)
					}
				} else {
					// When client service has no envCode, choose server services who have no envCode
					if !ok {
						nodes = append(nodes, node)
					}
				}
			}
			if len(nodes) > 0 {
				svc.Nodes = nodes
				got = append(got, svc)
			} else if len(noTagNodes) > 0 {
				svc.Nodes = noTagNodes
				noTagSvc = append(noTagSvc, svc)
			}
		}
		if !envStrict {
			// when client service has envCode, choose server services who have the same envCode. If there is no services, choose services who have no envCode and then choose whatever
			if len(got) == 0 {
				// no services found
				if len(noTagSvc) > 0 {
					got = noTagSvc //choose server service have no envCode
				} else {
					got = svcs // choose whatever
				}
			}
		}
		//printService("got is", got)
		return got
	}

	opts = append(opts, client.WithSelectOption(selector.WithFilter(envFilter)))

	return c.Client.Call(ctx, req, rsp, opts...)
}

```

more question:
* what wrong with the filter function above? the function exists when using gomicro v1.8.0 but panic when it upgrade to v4.5.0
* I have 15 rpc client nodes and 12 rpc server nodes. But only crash one of them everytime. If the bug comes from node info registering, all of the rpc client may crash.

**Comment by Davincible** [comment]
@gdgrc thanks for the extra information!

I am surprised to see a large number of `nil` nodes. I'd be curious to see when they exactly get added to the list.

As for the filter function, it is hard to say what is wrong, as I don't fully know you filter logic. However, I have refactored the filter function to make it easier to understand and debug. What is the panic you receive for the filter function exactly?

```go
// nodeFilter will filter nodes based envCode metadata tag
func nodeFilter(envCode string, envStrict bool) func([]*registry.Service) []*registry.Service {
	return func(svcs []*registry.Service) []*registry.Service {
		svcsTagged := make([]*registry.Service, 0)
		svcsUntagged := make([]*registry.Service, 0, len(svcs))

		for _, svc := range svcs {
			nodesTagged := make([]*registry.Node, 0, len(svc.Nodes))
			nodesUntagged := make([]*registry.Node, 0, len(svc.Nodes))

			for _, node := range svc.Nodes {
				env, ok := node.Metadata[envCode]

				// If metadata empty, node untagged
				if len(env) == 0 {
					nodesUntagged = append(nodesUntagged, node)
					continue
				}

				// when client service has envCode, choose server services who have the same envCode
				// When client service has no envCode, choose server services who have no envCode
				if (!ok && envCode == "") || (ok && env == envCode) {
					nodesTagged = append(nodesTagged, node)
				}
			}

			if len(nodesTagged) > 0 {
				svc.Nodes = nodesTagged
				svcsTagged = append(svcsTagged, svc)
			} else if len(nodesUntagged) > 0 {
				svc.Nodes = nodesUntagged
				svcsUntagged = append(svcsUntagged, svc)
			}
		}

		//printService("got is", got)

		// If strict or successfully filtered services
		if envStrict || len(svcsTagged) > 0 {
			return svcsTagged
		}

		// Choose services who have no envCode, if available
		if len(svcsUntagged) > 0 {
			return svcsUntagged
		}

		// Failed to filter nodes, choose whatever
		return svcs
	}
}

func (c *clientEnvCodeFilterWrap) Call(ctx context.Context, req client.Request, rsp interface{}, opts ...client.CallOption) (err error) {
	// Add function to filter target services according to metadata tag
	envFilter := nodeFilter(c.envCode, c.envStrict)
	opts = append(opts, client.WithSelectOption(selector.WithFilter(envFilter)))
	return c.Client.Call(ctx, req, rsp, opts...)
}
```

**Comment by Davincible** [comment]
In `cache.go`, the same file as your screenshots, could you add a log line in between line 254 and 255, something like this;

```go
if cur == nil {
    // Log line here
}
```

**Comment by gdgrc** [comment]
> @gdgrc thanks for the extra information!
> 
> I am surprised to see a large number of `nil` nodes. I'd be curious to see when they exactly get added to the list.
> 
> As for the filter function, it is hard to say what is wrong, as I don't fully know you filter logic. However, I have refactored the filter function to make it easier to understand and debug. What is the panic you receive for the filter function exactly?
> 
> ```go
> // nodeFilter will filter nodes based envCode metadata tag
> func nodeFilter(envCode string, envStrict bool) func([]*registry.Service) []*registry.Service {
> 	return func(svcs []*registry.Service) []*registry.Service {
> 		svcsTagged := make([]*registry.Service, 0)
> 		svcsUntagged := make([]*registry.Service, 0, len(svcs))
> 
> 		for _, svc := range svcs {
> 			nodesTagged := make([]*registry.Node, 0, len(svc.Nodes))
> 			nodesUntagged := make([]*registry.Node, 0, len(svc.Nodes))
> 
> 			for _, node := range svc.Nodes {
> 				env, ok := node.Metadata[envCode]
> 
> 				// If metadata empty, node untagged
> 				if len(env) == 0 {
> 					nodesUntagged = append(nodesUntagged, node)
> 					continue
> 				}
> 
> 				// when client service has envCode, choose server services who have the same envCode
> 				// When client service has no envCode, choose server services who have no envCode
> 				if (!ok && envCode == "") || (ok && env == envCode) {
> 					nodesTagged = append(nodesTagged, node)
> 				}
> 			}
> 
> 			if len(nodesTagged) > 0 {
> 				svc.Nodes = nodesTagged
> 				svcsTagged = append(svcsTagged, svc)
> 			} else if len(nodesUntagged) > 0 {
> 				svc.Nodes = nodesUntagged
> 				svcsUntagged = append(svcsUntagged, svc)
> 			}
> 		}
> 
> 		//printService("got is", got)
> 
> 		// If strict or successfully filtered services
> 		if envStrict || len(svcsTagged) > 0 {
> 			return svcsTagged
> 		}
> 
> 		// Choose services who have no envCode, if available
> 		if len(svcsUntagged) > 0 {
> 			return svcsUntagged
> 		}
> 
> 		// Failed to filter nodes, choose whatever
> 		return svcs
> 	}
> }
> 
> func (c *clientEnvCodeFilterWrap) Call(ctx context.Context, req client.Request, rsp interface{}, opts ...client.CallOption) (err error) {
> 	// Add function to filter target services according to metadata tag
> 	envFilter := nodeFilter(c.envCode, c.envStrict)
> 	opts = append(opts, client.WithSelectOption(selector.WithFilter(envFilter)))
> 	return c.Client.Call(ctx, req, rsp, opts...)
> }
> ```

q1: as I don't fully know you filter logic. 
The scene:  we provide services for  many company. But One of them have much more calls than others. So we set 6 server nodes specially for the one company to make services more stable.   The other 6 nodes deal with the normal flow.  As for the code, we use envCode to seperate them. We set 6 nodes as the special flow and the other 6 nodes are the normal flow. The calls of the normal flow will not call the special flow server group(unless all of the normal flow have been dead)

q2: What is the panic you receive for the filter function exactly?
we do not receive panic in the filter function. We receive panic only in ```/root/go/pkg/mod/go-micro.dev/v4@v4.5.0/util/registry/util.go:65 (0x10bab4c)```. We just suppose it may relate to the logic because 6 nodes are nil and we exactly make 2 group by the filter logic. 6 nodes  are special flow group  and the other 6 nodes  are normal flow group.

**Comment by gdgrc** [comment]
> 

![image](https://user-images.githubusercontent.com/18026719/193223991-3c2efb37-964d-4cbc-b475-a9669139502b.png)
Actually, the log here do not print anytime. so, it may not even have gone into this logic rathen then your expected logic.

**Comment by gdgrc** [comment]
@Davincible

**Comment by Davincible** [comment]
@gdgrc  Can you wrap your filter function with this, and check the logs:

```go
// WrapFilter will call the filter and log a message if it contains nil nodes
func WrapFilter(f func([]*registry.Service) []*registry.Service) func([]*registry.Service) []*registry.Service {
	return func(s []*registry.Service) []*registry.Service {
		if checkNilNode(s) {
			logger.Logf("[WARNING] Node filter received a list containing nil nodes from system: %+v", nodes)
		}

		nodes := f(s)

		if checkNilNode(s) {
			logger.Logf("[WARNING] Node filter returned a list containing nil nodes: %+v", nodes)
		}

		return nodes
	}
}

func checkNilNode(s []*registry.Service) bool {
	for _, node := range nodes {
		if node == nil {
			return true
		}
	}

	return false
}
```

**Comment by gdgrc** [comment]
> @gdgrc Can you wrap your filter function with this, and check the logs:
> 
> ```go
> // WrapFilter will call the filter and log a message if it contains nil nodes
> func WrapFilter(f func([]*registry.Service) []*registry.Service) func([]*registry.Service) []*registry.Service {
> 	return func(s []*registry.Service) []*registry.Service {
> 		if checkNilNode(s) {
> 			logger.Logf("[WARNING] Node filter received a list containing nil nodes from system: %+v", nodes)
> 		}
> 
> 		nodes := f(s)
> 
> 		if checkNilNode(s) {
> 			logger.Logf("[WARNING] Node filter returned a list containing nil nodes: %+v", nodes)
> 		}
> 
> 		return nodes
> 	}
> }
> 
> func checkNilNode(s []*registry.Service) bool {
> 	for _, node := range nodes {
> 		if node == nil {
> 			return true
> 		}
> 	}
> 
> 	return false
> }
> ```

We try to add etcd source node data fetch log in the next version.gomicro cache node data for 1m which means we get nodes data from etcd every minuete. We print the nodes data every minute.

**Comment by Davincible** [comment]
Well my point was to figure out if the bug is in go-micro itself, or in the filter function.

If we check if there are nil nodes after the custom selector, but not before (I forgot to add this part to the wrapper), then we know the selector is buggy, and not go-micro itself

**Comment by Davincible** [comment]
@gdgrc did you manage to track something down, or learn more about the issue?

**Comment by gdgrc** [comment]
@Davincible I add the code printing the source from etcd data.
![image](https://user-images.githubusercontent.com/18026719/200975343-61b8f401-aa27-4dee-b874-25ef280acd55.png)
("val" should be "version")

In the product env, we meat it again.Everything is good. The data from etcd is perfect.
```
[mylib] 2022/11/07 20:47:38 gomicro plugin GetService. isOldService: %!s(bool=true) version: latest
[mylib] 2022/11/07 20:47:38 gomicro plugin GetService every node: &{Id:account-8ed51584-bba2-467c-80cc-a12584d8ac23 Address:172.16.65.110:38089 Metadata:map[broker:http protocol:grpc registry:etcd server:grpc transport:grpc]}
[mylib] 2022/11/07 20:47:38 gomicro plugin GetService. isOldService: %!s(bool=true) version: latest
[mylib] 2022/11/07 20:47:38 gomicro plugin GetService every node: &{Id:account-9e5a906f-432a-478e-8bfe-52d7f8f85c74 Address:172.16.13.186:38089 Metadata:map[broker:http env_code:YSS protocol:grpc registry:etcd server:grpc transport:grpc]}
...
...
```
But panic as always: node with env_code turns to be nil
```
[mylib] 2022/11/07 20:47:39 gomicro inner panic sence every node: &{Id:account-8ed51584-bba2-467c-80cc-a12584d8ac23 Address:172.16.65.110:38089 Metadata:map[broker:http protocol:grpc registry:etcd server:grpc transport:grpc]}
[mylib] 2022/11/07 20:47:39 gomicro inner panic sence every node: <nil>
```

**Comment by gdgrc** [comment]
Anyway, the bug should be in the wrap logic.
1. maybe here: change the service directly.
```
if len(nodes) > 0 {
    svc.Nodes = nodes
    got = append(got, svc)
} else if len(noTagNodes) > 0 {
    svc.Nodes = noTagNodes
    noTagSvc = append(noTagSvc, svc)
}
```
2.maybe here. got should not append
```
if req.Service() != svc.Name {
	got = append(got, svc) //TODO: not necessary
	continue
}
```

**Comment by gdgrc** [comment]
By the way, I have fixed it with the frist way.

**Comment by Davincible** [comment]
Great to hear!! I will close this issue then.
