### ISSUE TITLE
How to log in JSON format ?

### ISSUE THREAD

**Issue by Adverax** [go-micro/go-micro#2550]
1. I tryed activate logging in JSON format.
2. I expected receive logging records in JSON format.
3. I received data in TEXT format.

I viewed the source code and in file debug/log/os.go I found lost call of function FORMAT. I think the code must be

```
func (o *osLog) Write(r Record) error {
	o.buffer.Put(o.format(r))
	return nil
}

```

**Comment by Davincible** [comment]
If you set your logger correctly there's no problem logging in json. What's your full logger setup code?

**Comment by Adverax** [comment]
Here is example code.

```
import (
	"go-micro.dev/v4/debug/log"
	"go-micro.dev/v4/logger"
)

func main() {
	log.DefaultLog = log.NewLog(
		log.Format(log.JSONFormat),
	)
	logger.Info("hello")
}
```

I traced execution of program and noticed that JSONFormat function was never called.

**Comment by Davincible** [comment]
I wouldn't use the `v4/debug/log` logger, see https://github.com/go-micro/plugins/tree/main/v4/logger for various loggers you can use. You can configure them to use JSON logging

**Comment by Adverax** [comment]
Thank you for your help. Have a good day!
