### ISSUE TITLE
Hello, may I ask why the body field of api.Endpoint should be removed?

### ISSUE THREAD

**Issue by Super-zhw** [go-micro/go-micro#2552]
If, remove the body field of api.Endpoint.
It may cause go-micro to not support the body field of "google.api.http", as follows:
```proto
service Demo {
  rpc SayHello(HelloRequest) returns (HelloResponse)
  {
    option (google.api.http) = {
      post: "/sayHello/{name}",
      body: "*" , // not support
    };
    option (grpc.gateway.protoc_gen_swagger.options.openapiv2_operation) = {
      description : "hello"
      summary : "hello"
    };
  }
  rpc Call(Request) returns (Response) {}
  rpc Stream(StreamingRequest) returns (stream StreamingResponse) {}
  rpc PingPong(stream Ping) returns (stream Pong) {}
}
```

If you specify go-micro as version 4.8.0, the "xx.pb.micro.go" file generated by the tool will report an error, indicating that api.Endpoint has no body field, as follows:

![image](https://user-images.githubusercontent.com/34789750/188462117-265ab93c-99aa-4bb5-8969-19da96fc599e.png)

https://github.com/asim/go-micro/commit/3381a9f3dba45f07a6dcdba163158c68a7bc4a89

**Comment by Davincible** [comment]
@asim

**Comment by asim** [comment]
Feel free to PR a fix to add it back
