### ISSUE TITLE
Store table initialization

### ISSUE THREAD

**Issue by sgnrslv** [go-micro/go-micro#2583]
[This code ](https://github.com/go-micro/go-micro/blob/c25dee7c8a7053743266c95b6a63a1b11ef3c1fb/service.go#L64) redefines store table provided via --store_table or $MICRO_STORE_TABLE for no reason.
And forces us to re-init store table later once again.

I think the previous approach (before [the commit ](https://github.com/go-micro/go-micro/commit/71538adfdcb00cb8e240c3b57471c55e74756e82)) was a correct one. What was the reason for this change?

**Comment by Davincible** [comment]
Honestly no clue. The easiest way to resolve this is by adding an extra option with a check to skip this. Would you be willing to create a PR?

**Comment by sgnrslv** [comment]
An extra option seems superfluous since providing store table via option or env variable can be treated already as an intention to have this exact table name. 

I think [the change](https://github.com/go-micro/go-micro/commit/71538adfdcb00cb8e240c3b57471c55e74756e82) was kind of an ad-hoc to remove the table specifying in cocroach plugin. But I see that this is not a problem anymore in [the plugin](https://github.com/go-micro/plugins/blob/main/v4/store/cockroach/cockroach.go#L62).

So it seems this will be OK:

```
		// If the store has no Table set, fallback to the
		// services name
		if len(store.DefaultStore.Options().Table) == 0 {
			name := s.opts.Cmd.App().Name
			store.DefaultStore.Init(store.Table(name))
		}
```

i.e. as it was before.

**Comment by Davincible** [comment]
You're right. Could you make a PR?
