### ISSUE TITLE
service not found while using api gateway

### ISSUE THREAD

**Issue by leoujz** [go-micro/go-micro#2587]
request: http://localhost:8080/helloworld/call
response: {"id":"go.micro.api","code":500,"detail":"service not found","status":"Internal Server Error"}

The Detailed reproducing step are posted in [the issue in go-micro/api repository](https://github.com/go-micro/api/issues/3)

Am I missing some steps or config?

**Comment by Davincible** [comment]
Hmm I'm not exactly sure, haven't used the API a lot.

The service not found would be a registry issue. Either not calling the correct service, or the service has not been registered.

You could try to use the client code, instead of cli,

**Comment by leoujz** [comment]
I might need some hints on how to run [go-micro/api, the api gateway](https://github.com/go-micro/api), according to README of go-micro/api, just install and run it, without any steps / configuration / codes on service side

**Comment by leoujz** [comment]
After some debugging, I have figured out that registering endpoints manually by code might be the necessary step, because when handling the request it will try to first match the endpoints of the default router, and then go to another way to resolve the service name and endpoint name, and in this process it use the METHOD value as the endpoint name, then report some error. (for `service not found` error, it resolve the service name as `go.micro.helloworld`) 
In my opinion, manually registering endpoints to the router would be a little tedious, because service and endpoint are already assigned in the HTTP request, auto resolving them would be a better way

**Comment by leoujz** [comment]
I think this issue can be closed now.

**Comment by Davincible** [comment]
I am glad you managed to find a solution. I agree that auto registration would be best.
Apologies for not giving you a better solution right now, most of our efforts are currently focused on v5.

If you ever find some time to dig into it contributions would be very welcome.

**Comment by leoujz** [comment]
It does not matter, thanks for your efforts on go-micro, really great repo. I will try to commit a pull request

**Comment by leoujz** [comment]
solve it with fixing endpoint name extraction when no endpoint matched, see https://github.com/go-micro/go-micro/pull/2592
