### ISSUE TITLE
How to import go-micro package with latest code in master branch?

### ISSUE THREAD

**Issue by leoujz** [go-micro/go-micro#2593]
Or else, if I want to develop on go-micro, how to deploy the environment. Just some hints would help

**Comment by leoujz** [comment]
Solved. `git clone` go-micro repo to the root of my project, and add `replace go-micro.dev/v4 => ./go-micro` to go.mod of my project, then it works. please close the issue

**Comment by xpunch** [comment]
Use Go Workspace in your local environment maybe the best solution.

**Comment by leoujz** [comment]
> Use Go Workspace in your local environment maybe the best solution.

thanks, I will try that

**Comment by Davincible** [comment]
I should to create a release :)

**Comment by leoujz** [comment]
this issue can be closed, thanks
