### ISSUE TITLE
[FEATURE] API gateway for gRPC service

### ISSUE THREAD

**Issue by leoujz** [go-micro/go-micro#2594]
I have tested api gateway for RPC service, that's really convenient, but failed to use it for gRPC service. 

Is there an api gateway for gRPC service? And I have known that [Transcoding HTTP/JSON to gRPC](https://cloud.google.com/endpoints/docs/grpc/transcoding) and [grpc-ecosystem/grpc-gateway](https://github.com/grpc-ecosystem/grpc-gateway), are these supported by go-micro or any other solution?

**Comment by Davincible** [comment]
I personally haven't tested them, but I guess it shouldn't be too difficult.

You could also try Traefik;
https://betterprogramming.pub/building-reverse-proxy-grpc-gateway-621696b29b0

**Comment by leoujz** [comment]
This tutorial would be better, https://earthly.dev/blog/golang-grpc-gateway/, with sample code and detailed instruction, I have tested this one in many choices.

I have no question about running rest proxy service seperately to communicate with the gRPC service, but my point is to integrate the REST http service in the same service of gRPC, finally I have a service with both REST and gRPC. This is already solved in above tutorial, but what I preferred is using go-micro to do that way, integrating go-micro gPRC and REST in one service.

Further more, is it possible to integrate REST service support into go-micro CLI, just like `go-micro new service helloworld --grpc`, and add an option like `go-micro new service helloworld --grpc --rest` in the future.

**Comment by leoujz** [comment]
maybe running REST seperately benefits from safety, that's ok. this issue can be closed. maybe take REST support into considerations of go-micro v5.

**Comment by Davincible** [comment]
@leoujz  v5 will natively support HTTP with the same proto handlers you use for gRPC as HTTP handlers out of the box ;)

Thanks for the link!
