### ISSUE TITLE
is it ok to use gRPC interceptors in go-micro

### ISSUE THREAD

**Issue by leoujz** [go-micro/go-micro#2595]
as the title

**Comment by Davincible** [comment]
Not sure about v4, never tried, you could try I guess, but it might be difficult since the server is tucked away a bit. v5 will support it out of the box

**Comment by Davincible** [comment]
Btw feel free to join the discord for any questions you have

**Comment by leoujz** [comment]
I will try discord

**Comment by leoujz** [comment]
Failed to try discord, I was not able to register it with a `resource limited` prompt, with twice tries. 

Really prefer to use go-micro framework in my new project, but the last problem in my way is interceptors, which I want to use to secure every gRPC call with my user authentication service. Any other solution? or any advice? Thanks very much.

Btw, when will v5 come out? I'm really looking forward to it.

**Comment by Davincible** [comment]
@leoujz You did you join the discord server twice, strange that you can't use it.

You can secure your services by requiring auth at the proxy level. I like to use Traefik's forward auth functionality for that, but I'm sure other reverse proxies also have auth build in.

If interceptors don't work with v4, you could also manually add the auth logic in your proto handlers temporarily.

v5 should be ready for testing in a month, or two. I'll be sure to let you know

**Comment by leoujz** [comment]
that's a solution. I'd rather wonder that at proxy level service mesh already has service discovery and registration, load balancing, what's the main difference or motivation of implemention in go-micro framework?
