### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by redscholar** [go-micro/go-micro#2599]
## Describe the bug
when i run service with profile. the error in service.Start() cannot catch or record.

## How to reproduce the bug
i think this code in defer change the error which return by  line 147 or line 161. should it be local variable?
https://github.com/go-micro/go-micro/blob/master/service.go#L151-L156

**Comment by Davincible** [comment]
Hmm I see.
Could you provide the code example you tested with?

**Comment by redscholar** [comment]
```go
func main() {
	//svc := option.InitService()
	svc := micro.NewService(
		micro.Name("test"),
		micro.Version("1.0.0"),
		micro.Address(":8080"),
		micro.Profile(http.NewProfile(profile.Name("web"))))
	svc.Init()
	if err := pbauth.RegisterAuthHandler(svc.Server(), handler.WireAuthHandler(svc)); err != nil {
		log.Fatalf("register AuthHandler error:%v", err)
	}
	if err := svc.Run(); err != nil {
		log.Fatalf("run micro.Service error:%v", err) 
	}
}
```

if port 8080 is already in use. svc.Run() will return nil

**Comment by Davincible** [comment]
Fixed. Until we create a full release, you can update to use the fix;

```bash
go get -u go-micro.dev/v4@master
```

Thanks for the report!
