### ISSUE TITLE
Why is the import path  v2 / v3/ v4 so confusing?

### ISSUE THREAD

**Issue by XieWeiXie** [go-micro/go-micro#2601]
Before asking, please check if your question has already been answered:

1. Check the documentation - https://micro.mu/docs/
2. Check the examples and plugins - https://github.com/micro/examples & https://github.com/micro/go-plugins
3. Search existing issues

v2: github.com/micro/go-micro/v2
v3: github.com/asim/go-micro/v3
v4:  go-micro.dev/v4

?

yeah. the old project recently prepared for upgrade go-micro , old version is v2 , new version is v4。

I can't even get started.

**Comment by Davincible** [comment]
Throughout the 7 years of development, the project has undergone a lot of improvements and changes and also moved around a bit. That is why the packages a named slightly differently.

However, anything older than v4 is currently not supported anymore. To get started you can look at the demo project, in the demo repo.

If you have any questions feel free to ask on Discord.
