### ISSUE TITLE
[FEATURE] Adding Sentry reporter

### ISSUE THREAD

**Issue by akhmadnurmuhammad** [go-micro/go-micro#2602]
**Is your feature request related to a problem? Please describe.**
Hi Guys, i'm really need adding sentry for error reporter but i cannot get recover error data because recover already called when program had error on this file https://github.com/go-micro/plugins/blob/0682c1c82ec59cf5c67c3f859e2e25e011ee0c7a/v4/server/grpc/grpc.go#L401

**Describe the solution you'd like**
if posible can we add 2 lines code of sentry like this image below
![image](https://user-images.githubusercontent.com/17354942/206647473-a5bb8513-d825-4fbe-b7ab-92b0d3205ba4.png)

**Additional context**

**Comment by Davincible** [comment]
Do you want to make a PR?

**Comment by akhmadnurmuhammad** [comment]
sure, please looking forward for my PR

**Comment by akhmadnurmuhammad** [comment]
please review my PR thanks 
https://github.com/go-micro/plugins/pull/87

**Comment by vcc-core** [comment]
This problem can be solved by multi output logger.

**Comment by Ak-Army** [comment]
This problem can be solved by a muti output logger.

**Comment by akhmadnurmuhammad** [comment]
i have try at handlerwrapper but still cannot get error because its already recover by go micro, or can you show me your code to solve this problem, i really appreciate thank you
