### ISSUE TITLE
How to set [tag] at service registration？如何在服务注册时设置tag属性？

### ISSUE THREAD

**Issue by zhanjunjie2019** [go-micro/go-micro#2611]
How to set [tag] at service registration？

My gateway configures dynamic routing based on service discovery （consul）. The configuration method is to define routing policies through the [tag] registered by the service.

However, I can't find the way that go-micro can set [tag] when registering the service.

The above is from translation.

-----------------------------------------------------------

如何在服务注册时设置tag属性？

我的网关基于服务发现来获取动态路由配置(consul)。配置时方式是在服务注册时，提供路由配置在tag属性上。

然而，我没找到可以在 go-micro 服务注册时如何设置tag属性。

**Comment by hellodudu** [comment]
You can try using metadata as an option for a service.

register service with custom tag data:
```go
metadata := make(map[string]string)
metadata["key"] = "value"

s.srv = micro.NewService(
  ...
  micro.Name(AppName),
  micro.Metadata(metadata),
  ...
)
```

then get service custom tag data from **registry.Service.Metadata**
