### ISSUE TITLE
how to set username and password in go micro broker mqtt

### ISSUE THREAD

**Issue by julianreza** [go-micro/go-micro#2622]
import (
	"strconv"
	"strings"

	mqtt "github.com/asim/go-micro/plugins/broker/mqtt/v4"
	"go-micro.dev/v4/broker"
)

Conn = broker.NewBroker(
	broker.Addrs(data.Address + ":" + strconv.Itoa(data.Port)),
)

error: bad user name or password

**Comment by asim** [comment]
File under plugins repo
