### ISSUE TITLE
Running on Windows 10 (x64)

### ISSUE THREAD

**Issue by lonnietc** [go-micro/go-micro#2639]
Hello All,

I am very new to Micro but think that it may hold promise for use in a highly scalable P2P application that I am working on since I really like what I have read so far although not sure what the difference between the "Micro" and "Go-Micro" repositories are at this moment.

Currently, I tried to follow a blog post "Building a global services network using Go, QUIC and Micro" (https://blog.gopheracademy.com/advent-2019/building-a-microservices-network/) [Dated 2019] to initial get up and running after compiling with Golang v1.19.3 on a Windows 10 (x64) which produced the micro.exe.

The blog said to connect with "micro.exe --peer" but there is no "peer" option and I do not know how to register and connect with micro.exe at this point?

Also, I am interested to know how well the micro network scales in addition to wanting to learn how to set up a private micro network for some development and testing purposes initially.

PS) I did find the Micro Discord Channel but there does not seem to be much activity.

Any help on these would be truly appreciated.
Best Regards and have a good day.

**Comment by asim** [comment]
Old issue, but Windows is not well supported sorry
