### ISSUE TITLE
What happen with github.com/micro/cli/v2 

### ISSUE THREAD

**Issue by ivybridge-3c33** [go-micro/go-micro#2641]
I got error 
github.com/micro/cli/v2@v2.1.2: invalid version: unknown revision v2.1.2

how to fix this?

**Comment by hhy5861** [comment]
@ivybridge-3c33 How did you solve it?

**Comment by morya** [comment]
cli was a copy from `github.com/urfave/cli/v2` and was not maintained quite well, and was dropped since.

you could replace it with `github.com/urfave/cli/v2`

**Comment by hhy5861** [comment]
> cli was a copy from `github.com/urfave/cli/v2` and was not maintained quite well, and was dropped since.
> 
> you could replace it with `github.com/urfave/cli/v2`

The way I'm handling it now is the same. It can only be done this way. Because the project hasn't been maintained for too long. Suddenly, there is a migration happening, and the code cannot be compiled.

**Comment by morya** [comment]
`go-micro/v4` is the latest stable version, better upgrade to it, or, you can just stick to old version without upgrade.
