### ISSUE TITLE
How to add authentication to go-micro/api?

### ISSUE THREAD

**Issue by ryanrain2016** [go-micro/go-micro#2644]
I want to add authentication to the gateway implemented with go-micro/api, but I don't know how to do it. Seems like the api doesn't implement something like middleware. Is there any other way to add an authentication method to the gateway?

**Comment by jochumdev** [comment]
https://github.com/jo-micro/auth2
https://github.com/jo-micro/router

Are changes to make Auth work in go-micro.

Else you might wait for go-orb to be done.
