### ISSUE TITLE
[BUG] micro.AddListenOption not working

### ISSUE THREAD

**Issue by ostoe** [go-micro/go-micro#2645]
## Describe the bug

1. What are you trying to do?
use my custom listener.
2. What did you expect to happen?
add my listener via `micro.AddListenOption`
```go
		micro.AddListenOption(func(o *server.Options) {
			o.ListenOptions = append(o.ListenOptions,
				func(lo *transport.ListenOptions) { lo.Context = ctx },
			)
		}),
```

3. What happens instead?
Nothing!

It will be never get the Listener from Context
# bug uri:  https://github.com/go-micro/go-micro/blob/80203030175fee9d982738b10a0cee7e3ad4a6ad/transport/context.go#L15

**Comment by ostoe** [comment]
ad

**Comment by jochumdev** [comment]
Still working on that? Any chance to give more context?
