### ISSUE TITLE
How can we ensure that the service node is Deregister wehn use zookeeper plugins

### ISSUE THREAD

**Issue by dingjianfeng** [go-micro/go-micro#2649]
When zookeeper plugins creates a node in the service registration discovery, the flag value is set 0, which means that the created node is a permanent path node. When the machine crashes or the kill 9 service process, how can we ensure that the service node is Deregister.

**Comment by jochumdev** [comment]
The only solution for that I see is either make ZooKeeper check the service (TCP port check) or by adding a 3rd party service that deregister's services which aren't there anymore.

When you add a 3rd party service you need to make sure to protect against split-brain ofc.

I'm writing this rudumentary as I haven't found any Zookeeper docs on doing health checks.
