### ISSUE TITLE
Advertise-address not work ? it is docker's ip  172.17.0.2 ??、

### ISSUE THREAD

**Issue by opvexe** [go-micro/go-micro#2651]
<img width="813" alt="image" src="https://github.com/go-micro/go-micro/assets/26895243/4ee55e9c-d9b7-4f5e-9d0b-431a549501c5">

**Comment by jochumdev** [comment]
Hi @shumintao 

How do you provide the `opts` to srv ?

**Comment by opvexe** [comment]
I had been solve
