### ISSUE TITLE
How can multiple subscribers on a topic only consume once

### ISSUE THREAD

**Issue by yurui2122** [go-micro/go-micro#2654]
Before asking, please check if your question has already been answered:

1. Check the documentation - https://micro.mu/docs/
2. Check the examples and plugins - https://github.com/micro/examples & https://github.com/micro/go-plugins
3. Search existing issues

**Comment by hellodudu** [comment]
Did you set **SubscribeOptions**'s option "Queue"? If so, try unset it.

```go
type SubscribeOptions struct {
	// AutoAck defaults to true. When a handler returns
	// with a nil error the message is acked.
	AutoAck bool
	// Subscribers with the same queue name
	// will create a shared subscription where each
	// receives a subset of messages.
	Queue string

	// Other options for implementations of the interface
	// can be stored in a context
	Context context.Context
}
```

http broker will set version as **broadcastVersion** if SubscribeOptions's Queue was set.
```go
// check for queue group or broadcast queue
version := options.Queue
if len(version) == 0 {
    version = broadcastVersion
}
```

broker will broadcast message to all subscriber if version was set as **broadcastVersion**.
```go
        switch service.Version {
	// broadcast version means broadcast to all nodes
	case broadcastVersion:
		var success bool

		// publish to all nodes
		for _, node := range nodes {
			// publish async
			if err := pub(node, topic, b); err == nil {
				success = true
			}
		}

		// save if it failed to publish at least once
		if !success {
			h.saveMessage(topic, b)
		}
	default:
		// select node to publish to
		node := nodes[rand.Int()%len(nodes)]

		// publish async to one node
		if err := pub(node, topic, b); err != nil {
			// if failed save it
			h.saveMessage(topic, b)
		}
	}
```

**Comment by yurui2122** [comment]
> Did you set **SubscribeOptions**'s option "Queue"? If so, try unset it.
> 
> ```go
> type SubscribeOptions struct {
> 	// AutoAck defaults to true. When a handler returns
> 	// with a nil error the message is acked.
> 	AutoAck bool
> 	// Subscribers with the same queue name
> 	// will create a shared subscription where each
> 	// receives a subset of messages.
> 	Queue string
> 
> 	// Other options for implementations of the interface
> 	// can be stored in a context
> 	Context context.Context
> }
> ```
> 
> http broker will set version as **broadcastVersion** if SubscribeOptions's Queue was set.
> 
> ```go
> // check for queue group or broadcast queue
> version := options.Queue
> if len(version) == 0 {
>     version = broadcastVersion
> }
> ```
> 
> broker will broadcast message to all subscriber if version was set as **broadcastVersion**.
> 
> ```go
>         switch service.Version {
> 	// broadcast version means broadcast to all nodes
> 	case broadcastVersion:
> 		var success bool
> 
> 		// publish to all nodes
> 		for _, node := range nodes {
> 			// publish async
> 			if err := pub(node, topic, b); err == nil {
> 				success = true
> 			}
> 		}
> 
> 		// save if it failed to publish at least once
> 		if !success {
> 			h.saveMessage(topic, b)
> 		}
> 	default:
> 		// select node to publish to
> 		node := nodes[rand.Int()%len(nodes)]
> 
> 		// publish async to one node
> 		if err := pub(node, topic, b); err != nil {
> 			// if failed save it
> 			h.saveMessage(topic, b)
> 		}
> 	}
> ```

ok，thanks

**Comment by yurui2122** [comment]
1

**Comment by yurui2122** [comment]
1
