### ISSUE TITLE
[BUG] Version V2.9.1 CLI no longer exists

### ISSUE THREAD

**Issue by hhy5861** [go-micro/go-micro#2669]
Version V2.9.1 CLI no longer exists. What is the way to solve this problem?

<img width="598" alt="image" src="https://github.com/go-micro/go-micro/assets/8274977/0f135d5d-9395-4390-b034-8dc093e08087">

**Comment by Scukerman** [comment]
I believe, that the only way is to upgrade to the latest version of this project. Like I did, but I stopped at v3.

**Comment by morya** [comment]
stick to the old version, unless you have to upgrade

**Comment by Scukerman** [comment]
@morya there's no old version anymore, the most of v2 packages are dead now. It's a blocker. The only way is to upgrade.

**Comment by morya** [comment]
go mod vendor it, or, you can push to a private repo and set a new tag, then use `replace` command inside go.mod to pin the version

**Comment by Scukerman** [comment]
Yeah, that's the solution in case if you want to keep all the same. But v2 and v3 have a lot of bugs. That's why I had to switch to v3 and fix the bugs myself. v3 is more stable than v2. At least all the packages are in place.
