### ISSUE TITLE
Tag latest v3 changes (v3.7.2)

### ISSUE THREAD

**Issue by Scukerman** [go-micro/go-micro#2672]
Hey guys,

Can you tag the latest changes on v3? I had a PR which fixes my problem but I still have to use my own fork with v3.7.2 tag to get around the issue.

The PR I'm talking about: https://github.com/go-micro/go-micro/pull/2600

**Comment by VegasCasino777** [comment]
I don't see the tag though

**Comment by Scukerman** [comment]
I don't see the tag though
