### ISSUE TITLE
go-micro v4版本   客户端请求超时，，在go-micro怎么配置请求时间

### ISSUE THREAD

**Issue by yz-yz-yz** [go-micro/go-micro#2689]
func init() {
	consulRegistry := consul.NewRegistry(
		//指定微服务的ip:  选择注册服务器地址,默认为本机,也可以选择consul集群中的client,建议一个微服务对应一个consul集群的client
		registry.Addrs("192.168.5.191:8500"),
	)
	// Create service
	srv := micro.NewService(
		micro.Registry(consulRegistry),
	)
	srv.Init()
	MicroClient = srv.Client()

}    这个是初始化客户端   -------------     \"id\":\"go.micro.client\",\"code\":408,\"detail\":\"call timeout: context deadline exceeded\",\"status\":\"Request Timeout\"}"

**Comment by dunzane** [comment]
same question

**Comment by asim** [comment]
In english please.
