### ISSUE TITLE
call Requset Timeout with detail <nil>

### ISSUE THREAD

**Issue by kanrin** [go-micro/go-micro#2694]
I'll call a client, but occasionally the request times out, but the information in the detail is <nil>
my log
` Retrying request. Previous attempt failed with: {"id":"go.micro.client","code":408,"detail":"\u003cnil\u003e","status":"Request Timeout"}`
This doesn't happen often, but it does happen occasionally

**Comment by kanrin** [comment]
use go-micro
"go-micro.dev/v4"

and client code
```
func Call(ctx context.Context, service *ServiceName, endpoint string, req any) error {
	c := client.NewClient(client.WithLogger(NewRpcLog()))
	if !service.Valid() {
		return fmt.Errorf("no valid service: %+v", service)
	}
	s, err := RandomGetService(service)
	if err != nil {
		return fmt.Errorf("get service error: %s", err)
	}
	rsp := new(message.Empty)
	if err := c.Call(ctx, c.NewRequest(s.Name, endpoint, req), rsp, client.WithRetries(0), client.WithRequestTimeout(time.Minute)); err != nil {
		return fmt.Errorf("call client:%s error:%s", s.Name, err)
	}
	if rsp.Count != 1 {
		klog.Debugf("rsp:%+v", rsp)
		return nil
	}
	return nil
}
```

empty struct such as
```
type Empty struct {
	Count int `json:"count"`
}
```

**Comment by asim** [comment]
Try setting retries higher than 0. Otherwise assuming stale entries in the registry, in which case you may want to try restart that or clear it out of stale entries, or use the TTL and heartbeat configuration.
