### ISSUE TITLE
Doesn't go-micro support lowercase grpc method name in proto ?

### ISSUE THREAD

**Issue by PerfecterDay** [go-micro/go-micro#2698]
### Discussed in https://github.com/go-micro/go-micro/discussions/2697

<div type='discussions-op-text'>

<sup>Originally posted by **PerfecterDay** March 14, 2024</sup>
Hi @asim , I have a proto file defined a rpcc service below :
```
service Greeter {
  rpc handle (Request) returns (Response) {
  }
}
```
in xxx.pb.micro.go, `Handle` method generated. And I have debug a little, find out go-micro use reflect to get the service name and method, and then register them in somewhere. 
but I see in xxx.pb.micro.go, it use lowercase method to gennerate request. This will lead 'unknown service Greeter.handle'
```
func (c *greeterService) Handle(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Greeter.handle", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}
```
So my question is does go-micro only support uppercase name ? Any suggetion will be appreciate</div>

**Comment by asim** [comment]
No, lowercase names are not supported. That would be a private method.
