### ISSUE TITLE
[BUG] v2 has no dependency to github.com/micro/cli/v2 v2.1.2

### ISSUE THREAD

**Issue by Caplost** [go-micro/go-micro#2704]
1. What are you trying to do?
I am attempting to compile my project after upgrading the dependency to github.com/micro/cli/v2 v2.1.2.

2. What did you expect to happen?
I expected the project to compile and run without issues.

3. What happens instead?
The compilation fails with an error indicating a problem with the module github.com/micro/cli/v2 v2.1.2, or that it is incompatible with other dependencies.

How to reproduce the bug
To reproduce the issue, follow these steps:
```
// Suppose you have a simple application that uses github.com/micro/cli/v2
package main

import (
    "github.com/micro/cli/v2"
)

func main() {
    // Example code, specifics depend on your application
    app := &cli.App{
        Commands: []*cli.Command{
            {
                Name: "example",
                Action: func(c *cli.Context) error {
                    return nil
                },
            },
        },
    }
    app.Run()
}

```

**Comment by asim** [comment]
Sorry v2 is no longer supported
