### ISSUE TITLE
How to use protobuf generation when upgrading go-micro from v4 to v5?

### ISSUE THREAD

**Issue by theexiile1305** [go-micro/go-micro#2726]
Good day,

First, many thanks `go-micro` team for this awesome project. 

I would like to upgrade _go-micro_ from version `v4.11.0` to version `v5.3.0`. This works quite well so far, but I have the question how I should use the protobuf generation?

My setup provides a Makefile for the generation of the protobuf code, in which the following dependencies are installed first:
```
go get -u google.golang.org/protobuf/proto@latest
go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
go install github.com/go-micro/generator/cmd/protoc-gen-micro@latest
```

Then `protoc --proto_path=./proto/ --micro_out=. --go_out=:. ./proto/*.proto` is called.

Unfortunately, I get the following error when compiling my code:

On further inspection of the generated code, you can see that the v4 of _go-micro_ is still being used and therefore the following questions arise for me:
- Which dependencies need an upgrade in this context? 
- How should the upgrade be carried out? 
- Are there any best practice recommendations for generating protobuf files?
- Is using https://buf.build/ as a build tool a good choice? Are there any examples or configuration recommendation to use it?

Many thanks and best regards
theexiile1305

**Comment by asim** [comment]
The generator has moved. Update it from here.

https://github.com/micro/go-micro/tree/master/cmd/protoc-gen-micro

`go install github.com/micro/go-micro/cmd/protoc-gen-micro`

**Comment by theexiile1305** [comment]
@asim Thank you very much for the quick response. The generation of the protobuf code is now working. 
However, I am still running into the following error when converting the plugins. Currently I use the registry etcd and the encoder yaml.

My plugins.go looks like this:
```
package main

import (
	_ “github.com/go-micro/plugins/v5/config/encoder/aml”
	_ “github.com/go-micro/plugins/v5/registry/etcd”
)
```

The error reads:
```
go: github.com/go-micro/plugins/v5/config/encoder/yaml@upgrade (v1.0.2) requires github.com/go-micro/plugins/v5/config/encoder/yaml@v1.0.2: parsing go.mod:
        module declares its path as: github.com/micro/plugins/v5/config/encoder/yaml
                but was required as: github.com/go-micro/plugins/v5/config/encoder/yaml
```

**Comment by asim** [comment]
Import path should be github.com/micro not github.com/go-micro

**Comment by theexiile1305** [comment]
@asim Thank you very much. The upgrades works as expected.
